package com.novacroft.nemo.tfl.common.constant.cyber_source;

/**
 * CyberSource Secure Acceptance HTTP POST payment gateway request fields
 */
public enum CyberSourcePostRequestField {
    ACCESS_KEY("access_key"),
    AMOUNT("amount"),
    BILL_TO_ADDRESS_CITY("bill_to_address_city"),
    BILL_TO_ADDRESS_COUNTRY("bill_to_address_country"),
    BILL_TO_ADDRESS_LINE1("bill_to_address_line1"),
    BILL_TO_ADDRESS_STATE("bill_to_address_state"),
    BILL_TO_EMAIL("bill_to_email"),
    BILL_TO_FORENAME("bill_to_forename"),
    BILL_TO_SURNAME("bill_to_surname"),
    CARD_EXPIRY_DATE("card_expiry_date"),
    CARD_NUMBER("card_number"),
    CARD_TYPE("card_type"),
    CURRENCY("currency"),
    LOCALE("locale"),
    PAYMENT_METHOD("payment_method"),
    PROFILE_ID("profile_id"),
    REFERENCE_NUMBER("reference_number"),
    SIGNATURE("signature"),
    SIGNED_DATE_TIME("signed_date_time"),
    SIGNED_FIELD_NAMES("signed_field_names"),
    TRANSACTION_TYPE("transaction_type"),
    TRANSACTION_UUID("transaction_uuid"),
    UNSIGNED_FIELD_NAMES("unsigned_field_names"),
    BILL_PAYMENT("bill_payment"),
    BILL_TO_ADDRESS_LINE2("bill_to_address_line2"),
    BILL_TO_ADDRESS_POSTAL_CODE("bill_to_address_postal_code"),
    BILL_TO_COMPANY_NAME("bill_to_company_name"),
    BILL_TO_PHONE("bill_to_phone"),
    CARD_CVN("card_cvn"),
    COMPANY_TAX_ID("company_tax_id"),
    COMPLETE_ROUTE("complete_route"),
    CONDITIONS_ACCEPTED("conditions_accepted"),
    CONSUMER_ID("consumer_id"),
    CUSTOMER_COOKIES_ACCEPTED("customer_cookies_accepted"),
    CUSTOMER_GIFT_WRAP("customer_gift_wrap"),
    CUSTOMER_IP_ADDRESS("customer_ip_address"),
    DATE_OF_BIRTH("date_of_birth"),
    DEBT_INDICATOR("debt_indicator"),
    DEPARTURE_TIME("departure_time"),
    DEVICE_FINGERPRINT_ID("device_fingerprint_id"),
    DRIVER_LICENSE_NUMBER("driver_license_number"),
    DRIVER_LICENSE_STATE("driver_license_state"),
    ECHECK_ACCOUNT_NUMBER("echeck_account_number"),
    ECHECK_ACCOUNT_TYPE("echeck_account_type"),
    ECHECK_CHECK_NUMBER("echeck_check_number"),
    ECHECK_ROUTING_NUMBER("echeck_routing_number"),
    ECHECK_SEC_CODE("echeck_sec_code"),
    IGNORE_AVS("ignore_avs"),
    IGNORE_CVN("ignore_cvn"),
    ITEM_1_CODE("item_1_code"),
    ITEM_1_NAME("item_1_name"),
    ITEM_1_QUANTITY("item_1_quantity"),
    ITEM_1_SKU("item_1_sku"),
    ITEM_1_TAX_AMOUN("item_1_tax_amoun"),
    ITEM_1_UNIT_PRICE("item_1_unit_price"),
    JOURNEY_LEG1_DEST("journey_leg1_dest"),
    JOURNEY_LEG1_ORIG("journey_leg1_orig"),
    JOURNEY_TYPE("journey_type"),
    LINE_ITEM_COUNT("line_item_count"),
    MERCHANT_DEFINED_DATA1("merchant_defined_data1"),
    MERCHANT_SECURE_DATA1("merchant_secure_data1"),
    MERCHANT_SECURE_DATA2("merchant_secure_data2"),
    MERCHANT_SECURE_DATA3("merchant_secure_data3"),
    MERCHANT_SECURE_DATA4("merchant_secure_data4"),
    OVERRIDE_CUSTOM_CANCEL_PAGE("override_custom_cancel_page"),
    OVERRIDE_CUSTOM_RECEIPT_PAGE("override_custom_receipt_page"),
    PAYMENT_TOKEN("payment_token"),
    PAYMENT_TOKEN_COMMEN("payment_token_commen"),
    PAYMENT_TOKEN_TITLE("payment_token_title"),
    RECURRING_AMOUNT("recurring_amount"),
    RECURRING_FREQUENCY("recurring_frequency"),
    RECURRING_NUMBER_OF_INSTALLMENTS("recurring_number_of_installments"),
    RECURRING_START_DATE("recurring_start_date"),
    RETURNS_ACCEPTED("returns_accepted"),
    SHIP_TO_ADDRESS_CITY("ship_to_address_city"),
    SHIP_TO_ADDRESS_COUNTRY("ship_to_address_country"),
    SHIP_TO_ADDRESS_LINE1("ship_to_address_line1"),
    SHIP_TO_ADDRESS_LINE2("ship_to_address_line2"),
    SHIP_TO_ADDRESS_POSTAL_CODE("ship_to_address_postal_code"),
    SHIP_TO_ADDRESS_STATE("ship_to_address_state"),
    SHIP_TO_COMPANY_NAME("ship_to_company_name"),
    SHIP_TO_FORENAME("ship_to_forename"),
    SHIP_TO_PHONE("ship_to_phone"),
    SHIP_TO_SURNAME("ship_to_surname"),
    SHIPPING_METHOD("shipping_method"),
    SKIP_DECISION_MANAGER("skip_decision_manager"),
    TAX_AMOUNT("tax_amount");

    private String code;

    private CyberSourcePostRequestField(String code) {
        this.code = code;
    }

    public String code() {
        return this.code;
    }
}
