package com.novacroft.nemo.tfl.common.constant.cyber_source;

/**
 * CyberSource Secure Acceptance HTTP POST payment gateway reply fields
 */
public enum CyberSourcePostReplyField {
    AUTH_AMOUNT("auth_amount"),
    AUTH_AVS_CODE("auth_avs_code"),
    AUTH_AVS_CODE_RAW("auth_avs_code_raw"),
    AUTH_CODE("auth_code"),
    AUTH_CV_RESULT("auth_cv_result"),
    AUTH_CV_RESULT_RAW("auth_cv_result_raw"),
    AUTH_RESPONSE("auth_response"),
    AUTH_TIME("auth_time"),
    AUTH_TRANS_REF_NO("auth_trans_ref_no"),
    BILL_TRANS_REF_NO("bill_trans_ref_no"),
    DECISION("decision"),
    ECHECK_DEBIT_REF_NO("echeck_debit_ref_no"),
    ECHECK_DEBIT_SUBMIT_TIME("echeck_debit_submit_time"),
    INVALID_FIELDS("invalid_fields"),
    MESSAGE("message"),
    PAYER_AUTHENTICATION_CAVV("payer_authentication_cavv"),
    PAYER_AUTHENTICATION_ECI("payer_authentication_eci"),
    PAYER_AUTHENTICATION_PROOF_XM("payer_authentication_proof_xm"),
    PAYER_AUTHENTICATION_UAD("payer_authentication_uad"),
    PAYER_AUTHENTICATION_UCI("payer_authentication_uci"),
    PAYER_AUTHENTICATION_XID("payer_authentication_xid"),
    PAYMENT_TOKEN("payment_token"),
    REASON_CODE("reason_code"),
    REQ_ACCESS_KEY("req_access_key"),
    REQ_AMOUNT("req_amount"),
    REQ_BILL_PAYMENT("req_bill_payment"),
    REQ_BILL_TO_ADDRESS_CITY("req_bill_to_address_city"),
    REQ_BILL_TO_ADDRESS_COUNTRY("req_bill_to_address_country"),
    REQ_BILL_TO_ADDRESS_LINE1("req_bill_to_address_line1"),
    REQ_BILL_TO_ADDRESS_LINE2("req_bill_to_address_line2"),
    REQ_BILL_TO_ADDRESS_POSTAL_CODE("req_bill_to_address_postal_code"),
    REQ_BILL_TO_ADDRESS_STATE("req_bill_to_address_state"),
    REQ_BILL_TO_COMPANY_NAME("req_bill_to_company_name"),
    REQ_BILL_TO_EMAIL("req_bill_to_email"),
    REQ_BILL_TO_FORENAME("req_bill_to_forename"),
    REQ_BILL_TO_PHONE("req_bill_to_phone"),
    REQ_BILL_TO_SURNAME("req_bill_to_surname"),
    REQ_CARD_EXPIRY_DATE("req_card_expiry_date"),
    REQ_CARD_NUMBER("req_card_number"),
    REQ_CARD_TYPE("req_card_type"),
    REQ_COMPANY_TAX_ID("req_company_tax_id"),
    REQ_COMPLETE_ROUTE("req_complete_route"),
    REQ_CONSUMER_ID("req_consumer_id"),
    REQ_CURRENCY("req_currency"),
    REQ_CUSTOMER_COOKIES_ACCEPTED("req_customer_cookies_accepted"),
    REQ_CUSTOMER_GIFT_WRAP("req_customer_gift_wrap"),
    REQ_CUSTOMER_IP_ADDRESS("req_customer_ip_address"),
    REQ_DATE_OF_BIRTH("req_date_of_birth"),
    REQ_DEBT_INDICATOR("req_debt_indicator"),
    REQ_DEPARTURE_TIME("req_departure_time"),
    REQ_DEVICE_FINGERPRINT_ID("req_device_fingerprint_id"),
    REQ_DRIVER_LICENSE_NUMBER("req_driver_license_number"),
    REQ_DRIVER_LICENSE_STATE("req_driver_license_state"),
    REQ_ECHECK_ACCOUNT_NUMBER("req_echeck_account_number"),
    REQ_ECHECK_ACCOUNT_TYPE("req_echeck_account_type"),
    REQ_ECHECK_CHECK_NUMBER("req_echeck_check_number"),
    REQ_ECHECK_ROUTING_NUMBER("req_echeck_routing_number"),
    REQ_ECHECK_SEC_CODE("req_echeck_sec_code"),
    REQ_IGNORE_AVS("req_ignore_avs"),
    REQ_IGNORE_CVN("req_ignore_cvn"),
    REQ_ITEM_1_CODE("req_item_1_code"),
    REQ_ITEM_1_NAME("req_item_1_name"),
    REQ_ITEM_1_QUANTITY("req_item_1_quantity"),
    REQ_ITEM_1_SKU("req_item_1_sku"),
    REQ_ITEM_1_TAX_AMOUNT("req_item_1_tax_amount"),
    REQ_ITEM_1_UNIT_PRICE("req_item_1_unit_price"),
    REQ_JOURNEY_LEG1_DEST("req_journey_leg1_dest"),
    REQ_JOURNEY_LEG1_ORIG("req_journey_leg1_orig"),
    REQ_JOURNEY_TYPE("req_journey_type"),
    REQ_LINE_ITEM_COUNT("req_line_item_count"),
    REQ_LOCALE("req_locale"),
    REQ_MERCHANT_DEFINED_DATA1("req_merchant_defined_data1"),
    REQ_MERCHANT_SECURE_DATA1("req_merchant_secure_data1"),
    REQ_MERCHANT_SECURE_DATA2("req_merchant_secure_data2"),
    REQ_MERCHANT_SECURE_DATA3("req_merchant_secure_data3"),
    REQ_MERCHANT_SECURE_DATA4("req_merchant_secure_data4"),
    REQ_OVERRIDE_CUSTOM_RECEIPT_PAGE("req_override_custom_receipt_page"),
    REQ_PAYMENT_METHOD("req_payment_method"),
    REQ_PAYMENT_TOKEN("req_payment_token"),
    REQ_PAYMENT_TOKEN_COMMENTS("req_payment_token_comments"),
    REQ_PAYMENT_TOKEN_TITLE("req_payment_token_title"),
    REQ_PROFILE_ID("req_profile_id"),
    REQ_RECURRING_AMOUNT("req_recurring_amount"),
    REQ_RECURRING_FREQUENCY("req_recurring_frequency"),
    REQ_RECURRING_NUMBER_OF_INSTALLMENTS("req_recurring_number_of_installments"),
    REQ_RECURRING_START_DATE("req_recurring_start_date"),
    REQ_REFERENCE_NUMBER("req_reference_number"),
    REQ_RETURNS_ACCEPTED("req_returns_accepted"),
    REQ_SHIP_TO_ADDRESS_CITY("req_ship_to_address_city"),
    REQ_SHIP_TO_ADDRESS_COUNTRY("req_ship_to_address_country"),
    REQ_SHIP_TO_ADDRESS_LINE1("req_ship_to_address_line1"),
    REQ_SHIP_TO_ADDRESS_LINE2("req_ship_to_address_line2"),
    REQ_SHIP_TO_ADDRESS_POSTAL_CODE("req_ship_to_address_postal_code"),
    REQ_SHIP_TO_ADDRESS_STATE("req_ship_to_address_state"),
    REQ_SHIP_TO_COMPANY_NAME("req_ship_to_company_name"),
    REQ_SHIP_TO_FORENAME("req_ship_to_forename"),
    REQ_SHIP_TO_PHONE("req_ship_to_phone"),
    REQ_SHIP_TO_SURNAME("req_ship_to_surname"),
    REQ_SHIPPING_METHOD("req_shipping_method"),
    REQ_SKIP_DECISION_MANAGER("req_skip_decision_manager"),
    REQ_TAX_AMOUNT("req_tax_amount"),
    REQ_TRANSACTION_TYPE("req_transaction_type"),
    REQ_TRANSACTION_UUID("req_transaction_uuid"),
    REQUIRED_FIELDS("required_fields"),
    SIGNATURE("signature"),
    SIGNED_DATE_TIME("signed_date_time"),
    SIGNED_FIELD_NAMES("signed_field_names"),
    SERVICE_FEE_AMOUNT("service_fee_amount"),
    SERVICE_FEE_RETURN_URL("service_fee_return_url"),
    TRANSACTION_ID("transaction_id");

    private String code;

    private CyberSourcePostReplyField(String code) {
        this.code = code;
    }

    public String code() {
        return this.code;
    }
}
