--liquibase formatted sql

--changeset Novacroft:11.0.105
CREATE TABLE ${schemaName}."JCP_INVESTIGATION"
("ID" NUMBER(38) NOT NULL CONSTRAINT "JCP_INVESTIGATION_PK" PRIMARY KEY
, "CREATEDUSERID" VARCHAR2(64) NOT NULL
, "CREATEDDATETIME" DATE NOT NULL
, "MODIFIEDUSERID" VARCHAR2(64)
, "MODIFIEDDATETIME" DATE
, "CARDID" NUMBER(38)
, "CARDNUMBER" VARCHAR2(12) NOT NULL
, "STARTDATE" DATE
, "EXPIRYDATE" DATE
, CONSTRAINT "JCP_INVESTIGATION_FK1" FOREIGN KEY ("CARDID") REFERENCES ${schemaName}."CARD"("ID")
)
TABLESPACE ${tableTablespace}
;

CREATE SEQUENCE ${schemaName}.JCP_INVESTIGATION_SEQ START WITH 1 INCREMENT BY 1 NOMAXVALUE;

COMMENT ON TABLE ${schemaName}."JCP_INVESTIGATION" IS 'This table used by TFL fraud team to investigate, who got more than 
	3 months job centre plus discount card';
COMMENT ON COLUMN ${schemaName}."JCP_INVESTIGATION"."ID" IS 'Surrogate primary key - generated from JCP_INVESTIGATION_SEQ sequence';
COMMENT ON COLUMN ${schemaName}."JCP_INVESTIGATION"."CREATEDUSERID" IS 'Who created the record';
COMMENT ON COLUMN ${schemaName}."JCP_INVESTIGATION"."CREATEDDATETIME" IS 'When (date and time) the record was created';
COMMENT ON COLUMN ${schemaName}."JCP_INVESTIGATION"."MODIFIEDUSERID" IS 'Who last modified the record';
COMMENT ON COLUMN ${schemaName}."JCP_INVESTIGATION"."MODIFIEDDATETIME" IS 'When (date and time) the record was last modified';
COMMENT ON COLUMN ${schemaName}."JCP_INVESTIGATION"."CARDID" IS 'Reference to card';
COMMENT ON COLUMN ${schemaName}."JCP_INVESTIGATION"."CARDNUMBER" IS 'Oyster card number';
COMMENT ON COLUMN ${schemaName}."JCP_INVESTIGATION"."STARTDATE" IS 'Current date';
COMMENT ON COLUMN ${schemaName}."JCP_INVESTIGATION"."EXPIRYDATE" IS 'Job centre plus discount expiry date';

CREATE TABLE ${schemaName}."JCP_INVESTIGATION_AUD"
("REV" NUMBER NOT NULL
, "REVTYPE" NUMBER NOT NULL
,"ID" NUMBER(38) NOT NULL
, "CREATEDUSERID" VARCHAR2(64)
, "CREATEDDATETIME" DATE
, "MODIFIEDUSERID" VARCHAR2(64)
, "MODIFIEDDATETIME" DATE
, "CARDID" NUMBER(38)
, "CARDNUMBER" VARCHAR2(12)
, "STARTDATE" DATE
, "EXPIRYDATE" DATE
)
TABLESPACE ${tableTablespace}
;

COMMENT ON TABLE ${schemaName}."JCP_INVESTIGATION_AUD" IS 'Audit records for JCP_INVESTIGATION table';
