--liquibase formatted sql

--changeset Novacroft:11.0.110 context:nemo_development
CREATE SEQUENCE ${schemaName}."OYSTERCARD_SEQ";

CREATE TABLE ${schemaName}."MOCK_OYSTERCARD"
("ID" NUMBER(38) NOT NULL CONSTRAINT "OYSTERCARD_PK" PRIMARY KEY
, "CREATEDUSERID" VARCHAR2(64) NOT NULL
, "CREATEDDATETIME" DATE NOT NULL
, "MODIFIEDUSERID" VARCHAR2(64)
, "MODIFIEDDATETIME" DATE
, "PRESTIGEID" VARCHAR2(64) NOT NULL UNIQUE
, "PHOTOCARDNUMBER" VARCHAR2(64)
, "REGISTERED" NUMBER
, "PASSENGERTYPE" VARCHAR2(64)
, "AUTOLOADSTATE" NUMBER
, "CARDCAPABILITY" NUMBER
, "CARDTYPE" NUMBER
, "CCCLOSTSTOLENDATETIME" DATE
, "CARDDEPOSIT" NUMBER
, "DISCOUNTENTITLEMENT1" VARCHAR2(64)
, "DISCOUNTEXPIRY1" DATE
, "DISCOUNTENTITLEMENT2" VARCHAR2(64)
, "DISCOUNTEXPIRY2" DATE
, "DISCOUNTENTITLEMENT3" VARCHAR2(64)
, "DISCOUNTEXPIRY3" DATE
, "TITLE" VARCHAR2(32)
, "FIRSTNAME" VARCHAR2(64)
, "MIDDLEINITIAL" VARCHAR2(1)
, "LASTNAME" VARCHAR2(64)
, "DAYTIMEPHONENUMBER" VARCHAR2(32)
, "HOUSENUMBER" VARCHAR2(10)
, "HOUSENAME" VARCHAR2(64)
, "STREET" VARCHAR2(64)
, "TOWN" VARCHAR2(64)
, "COUNTY" VARCHAR2(64)
, "POSTCODE" VARCHAR2(64)
, "EMAILADDRESS" VARCHAR2(64)
, "PASSWORD" VARCHAR2(64)
)
TABLESPACE ${tableTablespace}
;


COMMENT ON TABLE ${schemaName}."MOCK_OYSTERCARD" IS 'Oyster card applicant details';
COMMENT ON COLUMN ${schemaName}."MOCK_OYSTERCARD"."ID" IS 'Surrogate primary key - generated from OYSTERCARD_SEQ sequence';
COMMENT ON COLUMN ${schemaName}."MOCK_OYSTERCARD"."CREATEDUSERID" IS 'Who created the record';
COMMENT ON COLUMN ${schemaName}."MOCK_OYSTERCARD"."CREATEDDATETIME" IS 'When (date and time) the record was created';
COMMENT ON COLUMN ${schemaName}."MOCK_OYSTERCARD"."MODIFIEDUSERID" IS 'Who last modified the record';
COMMENT ON COLUMN ${schemaName}."MOCK_OYSTERCARD"."MODIFIEDDATETIME" IS 'When (date and time) the record was last modified';
COMMENT ON COLUMN ${schemaName}."MOCK_OYSTERCARD"."PRESTIGEID" IS 'The Oyster card number';
COMMENT ON COLUMN ${schemaName}."MOCK_OYSTERCARD"."PHOTOCARDNUMBER" IS 'The Oyster card photocard number';
COMMENT ON COLUMN ${schemaName}."MOCK_OYSTERCARD"."REGISTERED" IS 'Has the card been registered?';
COMMENT ON COLUMN ${schemaName}."MOCK_OYSTERCARD"."PASSENGERTYPE" IS 'The oyster card passenger type';
COMMENT ON COLUMN ${schemaName}."MOCK_OYSTERCARD"."AUTOLOADSTATE" IS 'The autoload state';
COMMENT ON COLUMN ${schemaName}."MOCK_OYSTERCARD"."CARDCAPABILITY" IS 'The Oyster card capability';
COMMENT ON COLUMN ${schemaName}."MOCK_OYSTERCARD"."CARDTYPE" IS 'The Oyster card type';
COMMENT ON COLUMN ${schemaName}."MOCK_OYSTERCARD"."CCCLOSTSTOLENDATETIME" IS 'When (date and time) the card was lost / stolen';
COMMENT ON COLUMN ${schemaName}."MOCK_OYSTERCARD"."CARDDEPOSIT" IS 'The oyster card deposit';
COMMENT ON COLUMN ${schemaName}."MOCK_OYSTERCARD"."DISCOUNTENTITLEMENT1" IS 'Discount entitlement 1';
COMMENT ON COLUMN ${schemaName}."MOCK_OYSTERCARD"."DISCOUNTEXPIRY1" IS 'Expiry date and time for entitlement 1';
COMMENT ON COLUMN ${schemaName}."MOCK_OYSTERCARD"."DISCOUNTENTITLEMENT2" IS 'Discount entitlement 2';
COMMENT ON COLUMN ${schemaName}."MOCK_OYSTERCARD"."DISCOUNTEXPIRY2" IS 'Expiry date and time for entitlement 2';
COMMENT ON COLUMN ${schemaName}."MOCK_OYSTERCARD"."DISCOUNTENTITLEMENT3" IS 'Discount entitlement 3';
COMMENT ON COLUMN ${schemaName}."MOCK_OYSTERCARD"."DISCOUNTEXPIRY3" IS 'Expiry date and time for entitlement 3';
COMMENT ON COLUMN ${schemaName}."MOCK_OYSTERCARD"."TITLE" IS 'Applicant title';
COMMENT ON COLUMN ${schemaName}."MOCK_OYSTERCARD"."FIRSTNAME" IS 'Applicant first name';
COMMENT ON COLUMN ${schemaName}."MOCK_OYSTERCARD"."MIDDLEINITIAL" IS 'Applicant middle initial';
COMMENT ON COLUMN ${schemaName}."MOCK_OYSTERCARD"."LASTNAME" IS 'Applicant last name';
COMMENT ON COLUMN ${schemaName}."MOCK_OYSTERCARD"."DAYTIMEPHONENUMBER" IS 'Applicant daytime phone number';
COMMENT ON COLUMN ${schemaName}."MOCK_OYSTERCARD"."HOUSENUMBER" IS 'Applicant house number';
COMMENT ON COLUMN ${schemaName}."MOCK_OYSTERCARD"."HOUSENAME" IS 'Applicant house name';
COMMENT ON COLUMN ${schemaName}."MOCK_OYSTERCARD"."STREET" IS 'Applicant street';
COMMENT ON COLUMN ${schemaName}."MOCK_OYSTERCARD"."TOWN" IS 'Applicant town';
COMMENT ON COLUMN ${schemaName}."MOCK_OYSTERCARD"."COUNTY" IS 'Applicant county';
COMMENT ON COLUMN ${schemaName}."MOCK_OYSTERCARD"."POSTCODE" IS 'Applicant postcode';
COMMENT ON COLUMN ${schemaName}."MOCK_OYSTERCARD"."EMAILADDRESS" IS 'Applicant email address';
COMMENT ON COLUMN ${schemaName}."MOCK_OYSTERCARD"."PASSWORD" IS 'Applicant email password';


CREATE SEQUENCE ${schemaName}."OYSTERCARDPREPAYTICKET_SEQ";

CREATE TABLE ${schemaName}."MOCK_OYSTERCARDPREPAYTICKET"
("ID" NUMBER(38) NOT NULL CONSTRAINT "PREPAYTICKET_PK" PRIMARY KEY
, "CREATEDUSERID" VARCHAR2(64) NOT NULL
, "CREATEDDATETIME" DATE NOT NULL
, "MODIFIEDUSERID" VARCHAR2(64)
, "MODIFIEDDATETIME" DATE
, "PRESTIGEID" VARCHAR2(64) NOT NULL UNIQUE
, "SLOTNUMBER1" NUMBER
, "PRODUCT1" VARCHAR2(64)
, "ZONE1" VARCHAR2(64)
, "STARTDATE1" DATE
, "EXPIRYDATE1" DATE
, "PASSENGERTYPE1" VARCHAR2(64)
, "DISCOUNT1" VARCHAR2(64)
, "STATE1" NUMBER
, "SLOTNUMBER2" NUMBER
, "PRODUCT2" VARCHAR2(64)
, "ZONE2" VARCHAR2(64)
, "STARTDATE2" DATE
, "EXPIRYDATE2" DATE
, "PASSENGERTYPE2" VARCHAR2(64)
, "DISCOUNT2" VARCHAR2(64)
, "STATE2" NUMBER
, "SLOTNUMBER3" NUMBER
, "PRODUCT3" VARCHAR2(64)
, "ZONE3" VARCHAR2(64)
, "STARTDATE3" DATE
, "EXPIRYDATE3" DATE
, "PASSENGERTYPE3" VARCHAR2(64)
, "DISCOUNT3" VARCHAR2(64)
, "STATE3" NUMBER
)
TABLESPACE ${tableTablespace}
;


COMMENT ON TABLE ${schemaName}."MOCK_OYSTERCARDPREPAYTICKET" IS 'Oyster card prepay ticket details';
COMMENT ON COLUMN ${schemaName}."MOCK_OYSTERCARDPREPAYTICKET"."ID" IS 'Surrogate primary key - generated from PREPAYTICKET_SEQ sequence';
COMMENT ON COLUMN ${schemaName}."MOCK_OYSTERCARDPREPAYTICKET"."CREATEDUSERID" IS 'Who created the record';
COMMENT ON COLUMN ${schemaName}."MOCK_OYSTERCARDPREPAYTICKET"."CREATEDDATETIME" IS 'When (date and time) the record was created';
COMMENT ON COLUMN ${schemaName}."MOCK_OYSTERCARDPREPAYTICKET"."MODIFIEDUSERID" IS 'Who last modified the record';
COMMENT ON COLUMN ${schemaName}."MOCK_OYSTERCARDPREPAYTICKET"."MODIFIEDDATETIME" IS 'When (date and time) the record was last modified';
COMMENT ON COLUMN ${schemaName}."MOCK_OYSTERCARDPREPAYTICKET"."PRESTIGEID" IS 'The Oyster card number';
COMMENT ON COLUMN ${schemaName}."MOCK_OYSTERCARDPREPAYTICKET"."SLOTNUMBER1" IS 'The prepay ticket slot number 1';
COMMENT ON COLUMN ${schemaName}."MOCK_OYSTERCARDPREPAYTICKET"."PRODUCT1" IS 'The prepay ticket product for slot 1';
COMMENT ON COLUMN ${schemaName}."MOCK_OYSTERCARDPREPAYTICKET"."ZONE1" IS 'The prepay ticket applicable zones for slot 1';
COMMENT ON COLUMN ${schemaName}."MOCK_OYSTERCARDPREPAYTICKET"."STARTDATE1" IS 'The prepay ticket start date for slot 1';
COMMENT ON COLUMN ${schemaName}."MOCK_OYSTERCARDPREPAYTICKET"."EXPIRYDATE1" IS 'The prepay ticket expiry date for slot 1';
COMMENT ON COLUMN ${schemaName}."MOCK_OYSTERCARDPREPAYTICKET"."PASSENGERTYPE1" IS 'The prepay ticket passenger type (adult / student) for slot 1';
COMMENT ON COLUMN ${schemaName}."MOCK_OYSTERCARDPREPAYTICKET"."DISCOUNT1" IS 'The prepay ticket discount, if any for slot 1';
COMMENT ON COLUMN ${schemaName}."MOCK_OYSTERCARDPREPAYTICKET"."STATE1" IS 'The prepay ticket state for slot 1';
COMMENT ON COLUMN ${schemaName}."MOCK_OYSTERCARDPREPAYTICKET"."SLOTNUMBER2" IS 'The prepay ticket slot number 2';
COMMENT ON COLUMN ${schemaName}."MOCK_OYSTERCARDPREPAYTICKET"."PRODUCT2" IS 'The prepay ticket product for slot 2';
COMMENT ON COLUMN ${schemaName}."MOCK_OYSTERCARDPREPAYTICKET"."ZONE2" IS 'The prepay ticket applicable zones for slot 2';
COMMENT ON COLUMN ${schemaName}."MOCK_OYSTERCARDPREPAYTICKET"."STARTDATE2" IS 'The prepay ticket start date for slot 2';
COMMENT ON COLUMN ${schemaName}."MOCK_OYSTERCARDPREPAYTICKET"."EXPIRYDATE2" IS 'The prepay ticket expiry date for slot 2';
COMMENT ON COLUMN ${schemaName}."MOCK_OYSTERCARDPREPAYTICKET"."PASSENGERTYPE2" IS 'The prepay ticket passenger type (adult / student) for slot 2';
COMMENT ON COLUMN ${schemaName}."MOCK_OYSTERCARDPREPAYTICKET"."DISCOUNT2" IS 'The prepay ticket discount, if any for slot 2';
COMMENT ON COLUMN ${schemaName}."MOCK_OYSTERCARDPREPAYTICKET"."STATE2" IS 'The prepay ticket state for slot 2';
COMMENT ON COLUMN ${schemaName}."MOCK_OYSTERCARDPREPAYTICKET"."SLOTNUMBER3" IS 'The prepay ticket slot number 3';
COMMENT ON COLUMN ${schemaName}."MOCK_OYSTERCARDPREPAYTICKET"."PRODUCT3" IS 'The prepay ticket product for slot 3';
COMMENT ON COLUMN ${schemaName}."MOCK_OYSTERCARDPREPAYTICKET"."ZONE3" IS 'The prepay ticket applicable zones for slot 3';
COMMENT ON COLUMN ${schemaName}."MOCK_OYSTERCARDPREPAYTICKET"."STARTDATE3" IS 'The prepay ticket start date for slot 3';
COMMENT ON COLUMN ${schemaName}."MOCK_OYSTERCARDPREPAYTICKET"."EXPIRYDATE3" IS 'The prepay ticket expiry date for slot 3';
COMMENT ON COLUMN ${schemaName}."MOCK_OYSTERCARDPREPAYTICKET"."PASSENGERTYPE3" IS 'The prepay ticket passenger type (adult / student) for slot 3';
COMMENT ON COLUMN ${schemaName}."MOCK_OYSTERCARDPREPAYTICKET"."DISCOUNT3" IS 'The prepay ticket discount, if any for slot 3';
COMMENT ON COLUMN ${schemaName}."MOCK_OYSTERCARDPREPAYTICKET"."STATE3" IS 'The prepay ticket state for slot 3';


CREATE SEQUENCE ${schemaName}."OYSTERCARDPREPAYVALUE_SEQ";

CREATE TABLE ${schemaName}."MOCK_OYSTERCARDPREPAYVALUE"
("ID" NUMBER(38) NOT NULL CONSTRAINT "PREPAYVALUE_PK" PRIMARY KEY
, "CREATEDUSERID" VARCHAR2(64) NOT NULL
, "CREATEDDATETIME" DATE NOT NULL
, "MODIFIEDUSERID" VARCHAR2(64)
, "MODIFIEDDATETIME" DATE
, "PRESTIGEID" VARCHAR2(64) NOT NULL UNIQUE
, "CURRENCY" NUMBER
, "BALANCE" NUMBER
)
TABLESPACE ${tableTablespace}
;


COMMENT ON TABLE ${schemaName}."MOCK_OYSTERCARDPREPAYVALUE" IS 'Oyster card prepay value details';
COMMENT ON COLUMN ${schemaName}."MOCK_OYSTERCARDPREPAYVALUE"."ID" IS 'Surrogate primary key - generated from PREPAYTICKET_SEQ sequence';
COMMENT ON COLUMN ${schemaName}."MOCK_OYSTERCARDPREPAYVALUE"."CREATEDUSERID" IS 'Who created the record';
COMMENT ON COLUMN ${schemaName}."MOCK_OYSTERCARDPREPAYVALUE"."CREATEDDATETIME" IS 'When (date and time) the record was created';
COMMENT ON COLUMN ${schemaName}."MOCK_OYSTERCARDPREPAYVALUE"."MODIFIEDUSERID" IS 'Who last modified the record';
COMMENT ON COLUMN ${schemaName}."MOCK_OYSTERCARDPREPAYVALUE"."MODIFIEDDATETIME" IS 'When (date and time) the record was last modified';
COMMENT ON COLUMN ${schemaName}."MOCK_OYSTERCARDPREPAYVALUE"."PRESTIGEID" IS 'The Oyster card number';
COMMENT ON COLUMN ${schemaName}."MOCK_OYSTERCARDPREPAYVALUE"."CURRENCY" IS 'The prepay value currency';
COMMENT ON COLUMN ${schemaName}."MOCK_OYSTERCARDPREPAYVALUE"."BALANCE" IS 'The prepay value in pence';


CREATE SEQUENCE ${schemaName}."OYSTERCARDPPTPENDING_SEQ";

CREATE TABLE ${schemaName}."MOCK_OYSTERCARDPPTPENDING"
("ID" NUMBER(38) NOT NULL CONSTRAINT "PREPAYTICKETPENDING_PK" PRIMARY KEY
, "CREATEDUSERID" VARCHAR2(64) NOT NULL
, "CREATEDDATETIME" DATE NOT NULL
, "MODIFIEDUSERID" VARCHAR2(64)
, "MODIFIEDDATETIME" DATE
, "PRESTIGEID" VARCHAR2(64) NOT NULL UNIQUE
, "REQUESTSEQUENCENUMBER1" NUMBER
, "REALTIMEFLAG1" VARCHAR2(1)
, "PRODUCTCODE1" NUMBER
, "PRODUCTPRICE1" NUMBER
, "CURRENCY1" NUMBER
, "STARTDATE1" DATE
, "EXPIRYDATE1" DATE
, "PICKUPLOCATION1" NUMBER
, "REQUESTSEQUENCENUMBER2" NUMBER
, "REALTIMEFLAG2" VARCHAR2(1)
, "PRODUCTCODE2" NUMBER
, "PRODUCTPRICE2" NUMBER
, "CURRENCY2" NUMBER
, "STARTDATE2" DATE
, "EXPIRYDATE2" DATE
, "PICKUPLOCATION2" NUMBER
, "REQUESTSEQUENCENUMBER3" NUMBER
, "REALTIMEFLAG3" VARCHAR2(1)
, "PRODUCTCODE3" NUMBER
, "PRODUCTPRICE3" NUMBER
, "CURRENCY3" NUMBER
, "STARTDATE3" DATE
, "EXPIRYDATE3" DATE
, "PICKUPLOCATION3" NUMBER
)
TABLESPACE ${tableTablespace}
;


COMMENT ON TABLE ${schemaName}."MOCK_OYSTERCARDPPTPENDING" IS 'Oyster card prepay ticket pending details';
COMMENT ON COLUMN ${schemaName}."MOCK_OYSTERCARDPPTPENDING"."ID" IS 'Surrogate primary key - generated from PREPAYTICKET_SEQ sequence';
COMMENT ON COLUMN ${schemaName}."MOCK_OYSTERCARDPPTPENDING"."CREATEDUSERID" IS 'Who created the record';
COMMENT ON COLUMN ${schemaName}."MOCK_OYSTERCARDPPTPENDING"."CREATEDDATETIME" IS 'When (date and time) the record was created';
COMMENT ON COLUMN ${schemaName}."MOCK_OYSTERCARDPPTPENDING"."MODIFIEDUSERID" IS 'Who last modified the record';
COMMENT ON COLUMN ${schemaName}."MOCK_OYSTERCARDPPTPENDING"."MODIFIEDDATETIME" IS 'When (date and time) the record was last modified';
COMMENT ON COLUMN ${schemaName}."MOCK_OYSTERCARDPPTPENDING"."PRESTIGEID" IS 'The Oyster card number';
COMMENT ON COLUMN ${schemaName}."MOCK_OYSTERCARDPPTPENDING"."REQUESTSEQUENCENUMBER1" IS 'The 1st request sequence number';
COMMENT ON COLUMN ${schemaName}."MOCK_OYSTERCARDPPTPENDING"."REALTIMEFLAG1" IS 'The 1st realtime flag';
COMMENT ON COLUMN ${schemaName}."MOCK_OYSTERCARDPPTPENDING"."PRODUCTCODE1" IS 'The 1st product code';
COMMENT ON COLUMN ${schemaName}."MOCK_OYSTERCARDPPTPENDING"."PRODUCTPRICE1" IS 'The 1st product price';
COMMENT ON COLUMN ${schemaName}."MOCK_OYSTERCARDPPTPENDING"."CURRENCY1" IS 'The 1st currency';
COMMENT ON COLUMN ${schemaName}."MOCK_OYSTERCARDPPTPENDING"."STARTDATE1" IS 'The 1st start date';
COMMENT ON COLUMN ${schemaName}."MOCK_OYSTERCARDPPTPENDING"."EXPIRYDATE1" IS 'The 1st expiry date';
COMMENT ON COLUMN ${schemaName}."MOCK_OYSTERCARDPPTPENDING"."PICKUPLOCATION1" IS 'The 1st pick-up location';
COMMENT ON COLUMN ${schemaName}."MOCK_OYSTERCARDPPTPENDING"."REQUESTSEQUENCENUMBER2" IS 'The 2nd request sequence number';
COMMENT ON COLUMN ${schemaName}."MOCK_OYSTERCARDPPTPENDING"."REALTIMEFLAG2" IS 'The 2nd realtime flag';
COMMENT ON COLUMN ${schemaName}."MOCK_OYSTERCARDPPTPENDING"."PRODUCTCODE2" IS 'The 2nd product code';
COMMENT ON COLUMN ${schemaName}."MOCK_OYSTERCARDPPTPENDING"."PRODUCTPRICE2" IS 'The 2nd product price';
COMMENT ON COLUMN ${schemaName}."MOCK_OYSTERCARDPPTPENDING"."CURRENCY2" IS 'The 2nd currency';
COMMENT ON COLUMN ${schemaName}."MOCK_OYSTERCARDPPTPENDING"."STARTDATE2" IS 'The 2nd start date';
COMMENT ON COLUMN ${schemaName}."MOCK_OYSTERCARDPPTPENDING"."EXPIRYDATE2" IS 'The 2nd expiry date';
COMMENT ON COLUMN ${schemaName}."MOCK_OYSTERCARDPPTPENDING"."PICKUPLOCATION2" IS 'The 2nd pick-up location';
COMMENT ON COLUMN ${schemaName}."MOCK_OYSTERCARDPPTPENDING"."REQUESTSEQUENCENUMBER3" IS 'The 3rd request sequence number';
COMMENT ON COLUMN ${schemaName}."MOCK_OYSTERCARDPPTPENDING"."REALTIMEFLAG3" IS 'The 3rd realtime flag';
COMMENT ON COLUMN ${schemaName}."MOCK_OYSTERCARDPPTPENDING"."PRODUCTCODE3" IS 'The 3rd product code';
COMMENT ON COLUMN ${schemaName}."MOCK_OYSTERCARDPPTPENDING"."PRODUCTPRICE3" IS 'The 3rd product price';
COMMENT ON COLUMN ${schemaName}."MOCK_OYSTERCARDPPTPENDING"."CURRENCY3" IS 'The 3rd currency';
COMMENT ON COLUMN ${schemaName}."MOCK_OYSTERCARDPPTPENDING"."STARTDATE3" IS 'The 3rd start date';
COMMENT ON COLUMN ${schemaName}."MOCK_OYSTERCARDPPTPENDING"."EXPIRYDATE3" IS 'The 3rd expiry date';
COMMENT ON COLUMN ${schemaName}."MOCK_OYSTERCARDPPTPENDING"."PICKUPLOCATION3" IS 'The 3rd pick-up location';


CREATE SEQUENCE ${schemaName}."OYSTERCARDPPVPENDING_SEQ";

CREATE TABLE ${schemaName}."MOCK_OYSTERCARDPPVPENDING"
("ID" NUMBER(38) NOT NULL CONSTRAINT "PREPAYVALUEPENDING_PK" PRIMARY KEY
, "CREATEDUSERID" VARCHAR2(64) NOT NULL
, "CREATEDDATETIME" DATE NOT NULL
, "MODIFIEDUSERID" VARCHAR2(64)
, "MODIFIEDDATETIME" DATE
, "PRESTIGEID" VARCHAR2(64) NOT NULL UNIQUE
, "REQUESTSEQUENCENUMBER" NUMBER
, "REALTIMEFLAG" VARCHAR2(1)
, "PREPAYVALUE" NUMBER
, "CURRENCY" NUMBER
, "PICKUPLOCATION" NUMBER
)
TABLESPACE ${tableTablespace}
;


COMMENT ON TABLE ${schemaName}."MOCK_OYSTERCARDPPVPENDING" IS 'Oyster card prepay ticket pending details';
COMMENT ON COLUMN ${schemaName}."MOCK_OYSTERCARDPPVPENDING"."ID" IS 'Surrogate primary key - generated from PREPAYTICKET_SEQ sequence';
COMMENT ON COLUMN ${schemaName}."MOCK_OYSTERCARDPPVPENDING"."CREATEDUSERID" IS 'Who created the record';
COMMENT ON COLUMN ${schemaName}."MOCK_OYSTERCARDPPVPENDING"."CREATEDDATETIME" IS 'When (date and time) the record was created';
COMMENT ON COLUMN ${schemaName}."MOCK_OYSTERCARDPPVPENDING"."MODIFIEDUSERID" IS 'Who last modified the record';
COMMENT ON COLUMN ${schemaName}."MOCK_OYSTERCARDPPVPENDING"."MODIFIEDDATETIME" IS 'When (date and time) the record was last modified';
COMMENT ON COLUMN ${schemaName}."MOCK_OYSTERCARDPPVPENDING"."PRESTIGEID" IS 'The Oyster card number';
COMMENT ON COLUMN ${schemaName}."MOCK_OYSTERCARDPPVPENDING"."REQUESTSEQUENCENUMBER" IS 'The request sequence number';
COMMENT ON COLUMN ${schemaName}."MOCK_OYSTERCARDPPVPENDING"."REALTIMEFLAG" IS 'The realtime flag';
COMMENT ON COLUMN ${schemaName}."MOCK_OYSTERCARDPPVPENDING"."PREPAYVALUE" IS 'The prepay value';
COMMENT ON COLUMN ${schemaName}."MOCK_OYSTERCARDPPVPENDING"."CURRENCY" IS 'The currency';
COMMENT ON COLUMN ${schemaName}."MOCK_OYSTERCARDPPVPENDING"."PICKUPLOCATION" IS 'The pick-up location';


CREATE SEQUENCE ${schemaName}."OYSTERCARDHOTLISTREASONS_SEQ";

CREATE TABLE ${schemaName}."MOCK_OYSTERCARDHOTLISTREASONS"
("ID" NUMBER(38) NOT NULL CONSTRAINT "HOTLISTREASONS_PK" PRIMARY KEY
, "CREATEDUSERID" VARCHAR2(64) NOT NULL
, "CREATEDDATETIME" DATE NOT NULL
, "MODIFIEDUSERID" VARCHAR2(64)
, "MODIFIEDDATETIME" DATE
, "PRESTIGEID" VARCHAR2(64) NOT NULL UNIQUE
, "HOTLISTREASONCODE" NUMBER
)
TABLESPACE ${tableTablespace}
;


COMMENT ON TABLE ${schemaName}."MOCK_OYSTERCARDHOTLISTREASONS" IS 'Oyster card prepay ticket pending details';
COMMENT ON COLUMN ${schemaName}."MOCK_OYSTERCARDHOTLISTREASONS"."ID" IS 'Surrogate primary key - generated from PREPAYTICKET_SEQ sequence';
COMMENT ON COLUMN ${schemaName}."MOCK_OYSTERCARDHOTLISTREASONS"."CREATEDUSERID" IS 'Who created the record';
COMMENT ON COLUMN ${schemaName}."MOCK_OYSTERCARDHOTLISTREASONS"."CREATEDDATETIME" IS 'When (date and time) the record was created';
COMMENT ON COLUMN ${schemaName}."MOCK_OYSTERCARDHOTLISTREASONS"."MODIFIEDUSERID" IS 'Who last modified the record';
COMMENT ON COLUMN ${schemaName}."MOCK_OYSTERCARDHOTLISTREASONS"."MODIFIEDDATETIME" IS 'When (date and time) the record was last modified';
COMMENT ON COLUMN ${schemaName}."MOCK_OYSTERCARDHOTLISTREASONS"."PRESTIGEID" IS 'The Oyster card number';
COMMENT ON COLUMN ${schemaName}."MOCK_OYSTERCARDHOTLISTREASONS"."HOTLISTREASONCODE" IS 'The hot list reason code';
