--liquibase formatted sql

--changeset Novacroft:11.0.87
INSERT INTO ${schemaName}.PTTIDLOOKUP
("ID", "CREATEDUSERID", "CREATEDDATETIME", "MODIFIEDUSERID", "MODIFIEDDATETIME","DESCRIPTION", "CREDIT", "DISPLAYDESCRIPTION")
VALUES(0, 'Installer', SYSDATE, NULL, NULL,'Unknown', 'N', 'Empty');

INSERT INTO ${schemaName}.PTTIDLOOKUP
("ID", "CREATEDUSERID", "CREATEDDATETIME", "MODIFIEDUSERID", "MODIFIEDDATETIME","DESCRIPTION", "CREDIT", "DISPLAYDESCRIPTION")
VALUES(58, 'Installer', SYSDATE, NULL, NULL,'Pay as you go cancelled', 'N', 'Pay as you go removed');

INSERT INTO ${schemaName}.PTTIDLOOKUP
("ID", "CREATEDUSERID", "CREATEDDATETIME", "MODIFIEDUSERID", "MODIFIEDDATETIME","DESCRIPTION", "CREDIT", "DISPLAYDESCRIPTION")
VALUES(60, 'Installer', SYSDATE, NULL, NULL,'Pay as you go adjusted', 'Y', 'Pay as you go balance adjusted');

INSERT INTO ${schemaName}.PTTIDLOOKUP
("ID", "CREATEDUSERID", "CREATEDDATETIME", "MODIFIEDUSERID", "MODIFIEDDATETIME","DESCRIPTION", "CREDIT", "DISPLAYDESCRIPTION")
VALUES(63, 'Installer', SYSDATE, NULL, NULL,'Charge corrected', 'Y', 'Journey auto-completed');

INSERT INTO ${schemaName}.PTTIDLOOKUP
("ID", "CREATEDUSERID", "CREATEDDATETIME", "MODIFIEDUSERID", "MODIFIEDDATETIME","DESCRIPTION", "CREDIT", "DISPLAYDESCRIPTION")
VALUES(64, 'Installer', SYSDATE, NULL, NULL,'Charge corrected', 'Y', 'Pay as you go balance corrected');

INSERT INTO ${schemaName}.PTTIDLOOKUP
("ID", "CREATEDUSERID", "CREATEDDATETIME", "MODIFIEDUSERID", "MODIFIEDDATETIME","DESCRIPTION", "CREDIT", "DISPLAYDESCRIPTION")
VALUES(65, 'Installer', SYSDATE, NULL, NULL,'Route validation', 'N', 'Touched pink card reader');

INSERT INTO ${schemaName}.PTTIDLOOKUP
("ID", "CREATEDUSERID", "CREATEDDATETIME", "MODIFIEDUSERID", "MODIFIEDDATETIME","DESCRIPTION", "CREDIT", "DISPLAYDESCRIPTION")
VALUES(500, 'Installer', SYSDATE, NULL, NULL,'Complete Journey', 'Y', 'Complete Journey');

INSERT INTO ${schemaName}.PTTIDLOOKUP
("ID", "CREATEDUSERID", "CREATEDDATETIME", "MODIFIEDUSERID", "MODIFIEDDATETIME","DESCRIPTION", "CREDIT", "DISPLAYDESCRIPTION")
VALUES(501, 'Installer', SYSDATE, NULL, NULL,'Unstarted Journey', 'Y', 'Unstarted Journey');

INSERT INTO ${schemaName}.PTTIDLOOKUP
("ID", "CREATEDUSERID", "CREATEDDATETIME", "MODIFIEDUSERID", "MODIFIEDDATETIME","DESCRIPTION", "CREDIT", "DISPLAYDESCRIPTION")
VALUES(502, 'Installer', SYSDATE, NULL, NULL,'Unfinished Journey', 'Y', 'Unfinished Journey');

INSERT INTO ${schemaName}.PTTIDLOOKUP
("ID", "CREATEDUSERID", "CREATEDDATETIME", "MODIFIEDUSERID", "MODIFIEDDATETIME","DESCRIPTION", "CREDIT", "DISPLAYDESCRIPTION")
VALUES(503, 'Installer', SYSDATE, NULL, NULL,'Start not registered', 'Y', 'Start not registered');

INSERT INTO ${schemaName}.PTTIDLOOKUP
("ID", "CREATEDUSERID", "CREATEDDATETIME", "MODIFIEDUSERID", "MODIFIEDDATETIME","DESCRIPTION", "CREDIT", "DISPLAYDESCRIPTION")
VALUES(504, 'Installer', SYSDATE, NULL, NULL,'End not registered', 'Y', 'End not registered');

INSERT INTO ${schemaName}.PTTIDLOOKUP
("ID", "CREATEDUSERID", "CREATEDDATETIME", "MODIFIEDUSERID", "MODIFIEDDATETIME","DESCRIPTION", "CREDIT", "DISPLAYDESCRIPTION")
VALUES(505, 'Installer', SYSDATE, NULL, NULL,'Same Station exit within 30 minutes', 'Y', 'Same Station exit within 30 minutes');

INSERT INTO ${schemaName}.PTTIDLOOKUP
("ID", "CREATEDUSERID", "CREATEDDATETIME", "MODIFIEDUSERID", "MODIFIEDDATETIME","DESCRIPTION", "CREDIT", "DISPLAYDESCRIPTION")
VALUES(54, 'Installer', SYSDATE, NULL, NULL,'Discount added to Oyster card', 'Y', 'Discount added to Oyster card');

INSERT INTO ${schemaName}.PTTIDLOOKUP
("ID", "CREATEDUSERID", "CREATEDDATETIME", "MODIFIEDUSERID", "MODIFIEDDATETIME","DESCRIPTION", "CREDIT", "DISPLAYDESCRIPTION")
VALUES(56, 'Installer', SYSDATE, NULL, NULL,'Season ticket bought', 'Y', 'Season ticket bought');

INSERT INTO ${schemaName}.PTTIDLOOKUP
("ID", "CREATEDUSERID", "CREATEDDATETIME", "MODIFIEDUSERID", "MODIFIEDDATETIME","DESCRIPTION", "CREDIT", "DISPLAYDESCRIPTION")
VALUES(57, 'Installer', SYSDATE, NULL, NULL,'Season ticket removed', 'Y', 'Season ticket removed');

INSERT INTO ${schemaName}.PTTIDLOOKUP
("ID", "CREATEDUSERID", "CREATEDDATETIME", "MODIFIEDUSERID", "MODIFIEDDATETIME","DESCRIPTION", "CREDIT", "DISPLAYDESCRIPTION")
VALUES(59, 'Installer', SYSDATE, NULL, NULL,'Oyster card cancelled', 'Y', 'Oyster card cancelled');

INSERT INTO ${schemaName}.PTTIDLOOKUP
("ID", "CREATEDUSERID", "CREATEDDATETIME", "MODIFIEDUSERID", "MODIFIEDDATETIME","DESCRIPTION", "CREDIT", "DISPLAYDESCRIPTION")
VALUES(10, 'Installer', SYSDATE, NULL, NULL,'Oyster card reported lost or stolen', 'Y', 'Oyster card reported lost or stolen');

INSERT INTO ${schemaName}.PTTIDLOOKUP
("ID", "CREATEDUSERID", "CREATEDDATETIME", "MODIFIEDUSERID", "MODIFIEDDATETIME","DESCRIPTION", "CREDIT", "DISPLAYDESCRIPTION")
VALUES(506, 'Installer', SYSDATE, NULL, NULL,'Pending Transaction', 'Y', 'Pending Transaction');

INSERT INTO ${schemaName}.PTTIDLOOKUP
("ID", "CREATEDUSERID", "CREATEDDATETIME", "MODIFIEDUSERID", "MODIFIEDDATETIME","DESCRIPTION", "CREDIT", "DISPLAYDESCRIPTION")
VALUES(508, 'Installer', SYSDATE, NULL, NULL,'Sythetic Transaction', 'Y', 'Manually Corrected');

INSERT INTO ${schemaName}.PTTIDLOOKUP
("ID", "CREATEDUSERID", "CREATEDDATETIME", "MODIFIEDUSERID", "MODIFIEDDATETIME","DESCRIPTION", "CREDIT", "DISPLAYDESCRIPTION")
VALUES(507, 'Installer', SYSDATE, NULL, NULL,'Sythetic Transaction', 'Y', 'Completed Journey');

INSERT INTO ${schemaName}.PTTIDLOOKUP
("ID", "CREATEDUSERID", "CREATEDDATETIME", "MODIFIEDUSERID", "MODIFIEDDATETIME","DESCRIPTION", "CREDIT", "DISPLAYDESCRIPTION")
VALUES(9, 'Installer', SYSDATE, NULL, NULL,'Pay as you go enabled', 'Y', 'Pay as you go enabled');

INSERT INTO ${schemaName}.PTTIDLOOKUP
("ID", "CREATEDUSERID", "CREATEDDATETIME", "MODIFIEDUSERID", "MODIFIEDDATETIME","DESCRIPTION", "CREDIT", "DISPLAYDESCRIPTION")
VALUES(2, 'Installer', SYSDATE, NULL, NULL,'Top-up', 'Y', 'Topped up');

INSERT INTO ${schemaName}.PTTIDLOOKUP
("ID", "CREATEDUSERID", "CREATEDDATETIME", "MODIFIEDUSERID", "MODIFIEDDATETIME","DESCRIPTION", "CREDIT", "DISPLAYDESCRIPTION")
VALUES(3, 'Installer', SYSDATE, NULL, NULL,'Pay as you go adjusted', 'Y', 'Pay as you go balance adjusted');

INSERT INTO ${schemaName}.PTTIDLOOKUP
("ID", "CREATEDUSERID", "CREATEDDATETIME", "MODIFIEDUSERID", "MODIFIEDDATETIME","DESCRIPTION", "CREDIT", "DISPLAYDESCRIPTION")
VALUES(4, 'Installer', SYSDATE, NULL, NULL,'Disable NTM card capabilities', 'Y', 'Disable NTM card capabilities');

INSERT INTO ${schemaName}.PTTIDLOOKUP
("ID", "CREATEDUSERID", "CREATEDDATETIME", "MODIFIEDUSERID", "MODIFIEDDATETIME","DESCRIPTION", "CREDIT", "DISPLAYDESCRIPTION")
VALUES(5, 'Installer', SYSDATE, NULL, NULL,'Cancel PPT', 'Y', 'Season ticket cancelled');

INSERT INTO ${schemaName}.PTTIDLOOKUP
("ID", "CREATEDUSERID", "CREATEDDATETIME", "MODIFIEDUSERID", "MODIFIEDDATETIME","DESCRIPTION", "CREDIT", "DISPLAYDESCRIPTION")
VALUES(6, 'Installer', SYSDATE, NULL, NULL,'Pay as you go cancelled', 'N', 'Pay as you go balance cancelled during refund application');

INSERT INTO ${schemaName}.PTTIDLOOKUP
("ID", "CREATEDUSERID", "CREATEDDATETIME", "MODIFIEDUSERID", "MODIFIEDDATETIME","DESCRIPTION", "CREDIT", "DISPLAYDESCRIPTION")
VALUES(7, 'Installer', SYSDATE, NULL, NULL,'Set discount entitlements', 'Y', 'Discount added to Oyster card');

INSERT INTO ${schemaName}.PTTIDLOOKUP
("ID", "CREATEDUSERID", "CREATEDDATETIME", "MODIFIEDUSERID", "MODIFIEDDATETIME","DESCRIPTION", "CREDIT", "DISPLAYDESCRIPTION")
VALUES(8, 'Installer', SYSDATE, NULL, NULL,'Set personal details', 'Y', 'Set personal details');

INSERT INTO ${schemaName}.PTTIDLOOKUP
("ID", "CREATEDUSERID", "CREATEDDATETIME", "MODIFIEDUSERID", "MODIFIEDDATETIME","DESCRIPTION", "CREDIT", "DISPLAYDESCRIPTION")
VALUES(11, 'Installer', SYSDATE, NULL, NULL,'Issue PPT', 'Y', 'Season ticket bought');

INSERT INTO ${schemaName}.PTTIDLOOKUP
("ID", "CREATEDUSERID", "CREATEDDATETIME", "MODIFIEDUSERID", "MODIFIEDDATETIME","DESCRIPTION", "CREDIT", "DISPLAYDESCRIPTION")
VALUES(12, 'Installer', SYSDATE, NULL, NULL,'Entry', 'N', 'Bus journey route');

INSERT INTO ${schemaName}.PTTIDLOOKUP
("ID", "CREATEDUSERID", "CREATEDDATETIME", "MODIFIEDUSERID", "MODIFIEDDATETIME","DESCRIPTION", "CREDIT", "DISPLAYDESCRIPTION")
VALUES(13, 'Installer', SYSDATE, NULL, NULL,'Entry', 'N', 'Entry');

INSERT INTO ${schemaName}.PTTIDLOOKUP
("ID", "CREATEDUSERID", "CREATEDDATETIME", "MODIFIEDUSERID", "MODIFIEDDATETIME","DESCRIPTION", "CREDIT", "DISPLAYDESCRIPTION")
VALUES(14, 'Installer', SYSDATE, NULL, NULL,'Validate exit', 'Y', 'Validate exit');

INSERT INTO ${schemaName}.PTTIDLOOKUP
("ID", "CREATEDUSERID", "CREATEDDATETIME", "MODIFIEDUSERID", "MODIFIEDDATETIME","DESCRIPTION", "CREDIT", "DISPLAYDESCRIPTION")
VALUES(16, 'Installer', SYSDATE, NULL, NULL,'Manually re-enable NTM card capabilities', 'Y', 'Manually re-enable NTM card capabilities');

INSERT INTO ${schemaName}.PTTIDLOOKUP
("ID", "CREATEDUSERID", "CREATEDDATETIME", "MODIFIEDUSERID", "MODIFIEDDATETIME","DESCRIPTION", "CREDIT", "DISPLAYDESCRIPTION")
VALUES(17, 'Installer', SYSDATE, NULL, NULL,'Cancel NTM card', 'Y', 'Oyster card cancelled');

INSERT INTO ${schemaName}.PTTIDLOOKUP
("ID", "CREATEDUSERID", "CREATEDDATETIME", "MODIFIEDUSERID", "MODIFIEDDATETIME","DESCRIPTION", "CREDIT", "DISPLAYDESCRIPTION")
VALUES(19, 'Installer', SYSDATE, NULL, NULL,'NTM card usage statistics', 'Y', 'NTM card usage statistics');

INSERT INTO ${schemaName}.PTTIDLOOKUP
("ID", "CREATEDUSERID", "CREATEDDATETIME", "MODIFIEDUSERID", "MODIFIEDDATETIME","DESCRIPTION", "CREDIT", "DISPLAYDESCRIPTION")
VALUES(20, 'Installer', SYSDATE, NULL, NULL,'Apply life expiry', 'Y', 'Apply life expiry');

INSERT INTO ${schemaName}.PTTIDLOOKUP
("ID", "CREATEDUSERID", "CREATEDDATETIME", "MODIFIEDUSERID", "MODIFIEDDATETIME","DESCRIPTION", "CREDIT", "DISPLAYDESCRIPTION")
VALUES(21, 'Installer', SYSDATE, NULL, NULL,'Change NTM card keys', 'Y', 'Change NTM card keys');

INSERT INTO ${schemaName}.PTTIDLOOKUP
("ID", "CREATEDUSERID", "CREATEDDATETIME", "MODIFIEDUSERID", "MODIFIEDDATETIME","DESCRIPTION", "CREDIT", "DISPLAYDESCRIPTION")
VALUES(22, 'Installer', SYSDATE, NULL, NULL,'Prestige enable NTM card', 'Y', 'Prestige enable NTM card');

INSERT INTO ${schemaName}.PTTIDLOOKUP
("ID", "CREATEDUSERID", "CREATEDDATETIME", "MODIFIEDUSERID", "MODIFIEDDATETIME","DESCRIPTION", "CREDIT", "DISPLAYDESCRIPTION")
VALUES(23, 'Installer', SYSDATE, NULL, NULL,'Prestige re-enable NTM card', 'Y', 'Prestige re-enable NTM card');

INSERT INTO ${schemaName}.PTTIDLOOKUP
("ID", "CREATEDUSERID", "CREATEDDATETIME", "MODIFIEDUSERID", "MODIFIEDDATETIME","DESCRIPTION", "CREDIT", "DISPLAYDESCRIPTION")
VALUES(24, 'Installer', SYSDATE, NULL, NULL,'Prestige initialise NTM card', 'Y', 'Prestige initialise NTM card');

INSERT INTO ${schemaName}.PTTIDLOOKUP
("ID", "CREATEDUSERID", "CREATEDDATETIME", "MODIFIEDUSERID", "MODIFIEDDATETIME","DESCRIPTION", "CREDIT", "DISPLAYDESCRIPTION")
VALUES(25, 'Installer', SYSDATE, NULL, NULL,'Issue personalised NTM card', 'Y', 'Issue personalised NTM card');

INSERT INTO ${schemaName}.PTTIDLOOKUP
("ID", "CREATEDUSERID", "CREATEDDATETIME", "MODIFIEDUSERID", "MODIFIEDDATETIME","DESCRIPTION", "CREDIT", "DISPLAYDESCRIPTION")
VALUES(26, 'Installer', SYSDATE, NULL, NULL,'RTD accounting period', 'Y', 'RTD accounting period');

INSERT INTO ${schemaName}.PTTIDLOOKUP
("ID", "CREATEDUSERID", "CREATEDDATETIME", "MODIFIEDUSERID", "MODIFIEDDATETIME","DESCRIPTION", "CREDIT", "DISPLAYDESCRIPTION")
VALUES(27, 'Installer', SYSDATE, NULL, NULL,'RTD operation', 'Y', 'RTD operation');

INSERT INTO ${schemaName}.PTTIDLOOKUP
("ID", "CREATEDUSERID", "CREATEDDATETIME", "MODIFIEDUSERID", "MODIFIEDDATETIME","DESCRIPTION", "CREDIT", "DISPLAYDESCRIPTION")
VALUES(28, 'Installer', SYSDATE, NULL, NULL,'RTD power fail detected', 'Y', 'RTD power fail detected');

INSERT INTO ${schemaName}.PTTIDLOOKUP
("ID", "CREATEDUSERID", "CREATEDDATETIME", "MODIFIEDUSERID", "MODIFIEDDATETIME","DESCRIPTION", "CREDIT", "DISPLAYDESCRIPTION")
VALUES(29, 'Installer', SYSDATE, NULL, NULL,'Emirates Air Line ticket bought using pay as you go', 'Y', 'Emirates Air Line ticket bought using pay as you go');

INSERT INTO ${schemaName}.PTTIDLOOKUP
("ID", "CREATEDUSERID", "CREATEDDATETIME", "MODIFIEDUSERID", "MODIFIEDDATETIME","DESCRIPTION", "CREDIT", "DISPLAYDESCRIPTION")
VALUES(30, 'Installer', SYSDATE, NULL, NULL,'Issue transferable NTM card', 'Y', 'Issue transferable NTM card');

INSERT INTO ${schemaName}.PTTIDLOOKUP
("ID", "CREATEDUSERID", "CREATEDDATETIME", "MODIFIEDUSERID", "MODIFIEDDATETIME","DESCRIPTION", "CREDIT", "DISPLAYDESCRIPTION")
VALUES(31, 'Installer', SYSDATE, NULL, NULL,'Void purchase using pay as you go', 'Y', 'Void purchase using pay as you go');

INSERT INTO ${schemaName}.PTTIDLOOKUP
("ID", "CREATEDUSERID", "CREATEDDATETIME", "MODIFIEDUSERID", "MODIFIEDDATETIME","DESCRIPTION", "CREDIT", "DISPLAYDESCRIPTION")
VALUES(32, 'Installer', SYSDATE, NULL, NULL,'Void entry', 'Y', 'Void entry');

INSERT INTO ${schemaName}.PTTIDLOOKUP
("ID", "CREATEDUSERID", "CREATEDDATETIME", "MODIFIEDUSERID", "MODIFIEDDATETIME","DESCRIPTION", "CREDIT", "DISPLAYDESCRIPTION")
VALUES(33, 'Installer', SYSDATE, NULL, NULL,'Void exit', 'Y', 'Void exit');

INSERT INTO ${schemaName}.PTTIDLOOKUP
("ID", "CREATEDUSERID", "CREATEDDATETIME", "MODIFIEDUSERID", "MODIFIEDDATETIME","DESCRIPTION", "CREDIT", "DISPLAYDESCRIPTION")
VALUES(34, 'Installer', SYSDATE, NULL, NULL,'Void bus boarding', 'Y', 'Void bus boarding');

INSERT INTO ${schemaName}.PTTIDLOOKUP
("ID", "CREATEDUSERID", "CREATEDDATETIME", "MODIFIEDUSERID", "MODIFIEDDATETIME","DESCRIPTION", "CREDIT", "DISPLAYDESCRIPTION")
VALUES(35, 'Installer', SYSDATE, NULL, NULL,'Void issue PPT', 'Y', 'Season ticket removed');

INSERT INTO ${schemaName}.PTTIDLOOKUP
("ID", "CREATEDUSERID", "CREATEDDATETIME", "MODIFIEDUSERID", "MODIFIEDDATETIME","DESCRIPTION", "CREDIT", "DISPLAYDESCRIPTION")
VALUES(36, 'Installer', SYSDATE, NULL, NULL,'Pay as you go cancelled', 'N', 'Pay as you go removed');

INSERT INTO ${schemaName}.PTTIDLOOKUP
("ID", "CREATEDUSERID", "CREATEDDATETIME", "MODIFIEDUSERID", "MODIFIEDDATETIME","DESCRIPTION", "CREDIT", "DISPLAYDESCRIPTION")
VALUES(37, 'Installer', SYSDATE, NULL, NULL,'Riverboat ticket bought using pay as you go', 'Y', 'Riverboat ticket bought using pay as you go');

INSERT INTO ${schemaName}.PTTIDLOOKUP
("ID", "CREATEDUSERID", "CREATEDDATETIME", "MODIFIEDUSERID", "MODIFIEDDATETIME","DESCRIPTION", "CREDIT", "DISPLAYDESCRIPTION")
VALUES(38, 'Installer', SYSDATE, NULL, NULL,'Void purchase cash ticket using pay as you go', 'Y', 'Riverboat/Air Line transaction cancelled');

INSERT INTO ${schemaName}.PTTIDLOOKUP
("ID", "CREATEDUSERID", "CREATEDDATETIME", "MODIFIEDUSERID", "MODIFIEDDATETIME","DESCRIPTION", "CREDIT", "DISPLAYDESCRIPTION")
VALUES(39, 'Installer', SYSDATE, NULL, NULL,'Entry cancelled', 'Y', 'Previous touch in cancelled');

INSERT INTO ${schemaName}.PTTIDLOOKUP
("ID", "CREATEDUSERID", "CREATEDDATETIME", "MODIFIEDUSERID", "MODIFIEDDATETIME","DESCRIPTION", "CREDIT", "DISPLAYDESCRIPTION")
VALUES(40, 'Installer', SYSDATE, NULL, NULL,'Exit cancelled', 'N', 'Previous touch out cancelled');

INSERT INTO ${schemaName}.PTTIDLOOKUP
("ID", "CREATEDUSERID", "CREATEDDATETIME", "MODIFIEDUSERID", "MODIFIEDDATETIME","DESCRIPTION", "CREDIT", "DISPLAYDESCRIPTION")
VALUES(41, 'Installer', SYSDATE, NULL, NULL,'Entry cancelled', 'Y', 'Bus touch in cancelled');

INSERT INTO ${schemaName}.PTTIDLOOKUP
("ID", "CREATEDUSERID", "CREATEDDATETIME", "MODIFIEDUSERID", "MODIFIEDDATETIME","DESCRIPTION", "CREDIT", "DISPLAYDESCRIPTION")
VALUES(42, 'Installer', SYSDATE, NULL, NULL,'Top-up', 'Y', 'Topped-up on touch in');

INSERT INTO ${schemaName}.PTTIDLOOKUP
("ID", "CREATEDUSERID", "CREATEDDATETIME", "MODIFIEDUSERID", "MODIFIEDDATETIME","DESCRIPTION", "CREDIT", "DISPLAYDESCRIPTION")
VALUES(43, 'Installer', SYSDATE, NULL, NULL,'Ad-hoc issue PPT', 'Y', 'Season ticket added on touch in');

INSERT INTO ${schemaName}.PTTIDLOOKUP
("ID", "CREATEDUSERID", "CREATEDDATETIME", "MODIFIEDUSERID", "MODIFIEDDATETIME","DESCRIPTION", "CREDIT", "DISPLAYDESCRIPTION")
VALUES(44, 'Installer', SYSDATE, NULL, NULL,'Auto top-up configuration', 'Y', 'Auto top-up configuration');

INSERT INTO ${schemaName}.PTTIDLOOKUP
("ID", "CREATEDUSERID", "CREATEDDATETIME", "MODIFIEDUSERID", "MODIFIEDDATETIME","DESCRIPTION", "CREDIT", "DISPLAYDESCRIPTION")
VALUES(45, 'Installer', SYSDATE, NULL, NULL,'Auto top-up', 'Y', 'Auto top-up');

INSERT INTO ${schemaName}.PTTIDLOOKUP
("ID", "CREATEDUSERID", "CREATEDDATETIME", "MODIFIEDUSERID", "MODIFIEDDATETIME","DESCRIPTION", "CREDIT", "DISPLAYDESCRIPTION")
VALUES(46, 'Installer', SYSDATE, NULL, NULL,'Failed Ad-hoc/Auto top-up action', 'Y', 'Failed Ad-hoc/Auto top-up action');

INSERT INTO ${schemaName}.PTTIDLOOKUP
("ID", "CREATEDUSERID", "CREATEDDATETIME", "MODIFIEDUSERID", "MODIFIEDDATETIME","DESCRIPTION", "CREDIT", "DISPLAYDESCRIPTION")
VALUES(47, 'Installer', SYSDATE, NULL, NULL,'Entry', 'N', 'Entered');

INSERT INTO ${schemaName}.PTTIDLOOKUP
("ID", "CREATEDUSERID", "CREATEDDATETIME", "MODIFIEDUSERID", "MODIFIEDDATETIME","DESCRIPTION", "CREDIT", "DISPLAYDESCRIPTION")
VALUES(48, 'Installer', SYSDATE, NULL, NULL,'Entry cancelled', 'Y', 'Tramstop touch in cancelled');

INSERT INTO ${schemaName}.PTTIDLOOKUP
("ID", "CREATEDUSERID", "CREATEDDATETIME", "MODIFIEDUSERID", "MODIFIEDDATETIME","DESCRIPTION", "CREDIT", "DISPLAYDESCRIPTION")
VALUES(49, 'Installer', SYSDATE, NULL, NULL,'Exit', 'Y', 'Touch out');

INSERT INTO ${schemaName}.PTTIDLOOKUP
("ID", "CREATEDUSERID", "CREATEDDATETIME", "MODIFIEDUSERID", "MODIFIEDDATETIME","DESCRIPTION", "CREDIT", "DISPLAYDESCRIPTION")
VALUES(55, 'Installer', SYSDATE, NULL, NULL,'Card not touched out', 'Y', 'Journey auto-completed');

INSERT INTO ${schemaName}.PTTIDLOOKUP
("ID", "CREATEDUSERID", "CREATEDDATETIME", "MODIFIEDUSERID", "MODIFIEDDATETIME","DESCRIPTION", "CREDIT", "DISPLAYDESCRIPTION")
VALUES(61, 'Installer', SYSDATE, NULL, NULL,'Entry', 'N', 'Touch in');

INSERT INTO ${schemaName}.PTTIDLOOKUP
("ID", "CREATEDUSERID", "CREATEDDATETIME", "MODIFIEDUSERID", "MODIFIEDDATETIME","DESCRIPTION", "CREDIT", "DISPLAYDESCRIPTION")
VALUES(62, 'Installer', SYSDATE, NULL, NULL,'Exit', 'Y', 'Touch out');
