--liquibase formatted sql

--changeset Novacroft:11.0.4
CREATE TABLE ${schemaName}."SELECTLIST"
( "ID" NUMBER NOT NULL CONSTRAINT "SELECTLIST_PK" PRIMARY KEY
, "CREATEDUSERID" VARCHAR2(64) NOT NULL
, "CREATEDDATETIME" DATE NOT NULL
, "MODIFIEDUSERID" VARCHAR2(64)
, "MODIFIEDDATETIME" DATE
, "NAME" VARCHAR2(64) NOT NULL CONSTRAINT "SELECTLIST_UK1" UNIQUE
, "DESCRIPTION" VARCHAR2(1024)
)
TABLESPACE ${tableTablespace}
;

CREATE SEQUENCE ${schemaName}."SELECTLIST_SEQ";

COMMENT ON TABLE ${schemaName}."SELECTLIST" IS 'HTML select list data';
COMMENT ON COLUMN ${schemaName}."SELECTLIST"."ID" IS 'Surrogate primary key - generated from SELECTLIST_SEQ sequence';
COMMENT ON COLUMN ${schemaName}."SELECTLIST"."CREATEDUSERID" IS 'Who created the record';
COMMENT ON COLUMN ${schemaName}."SELECTLIST"."CREATEDDATETIME" IS 'When (date and time) the record was created';
COMMENT ON COLUMN ${schemaName}."SELECTLIST"."MODIFIEDUSERID" IS 'Who last modified the record';
COMMENT ON COLUMN ${schemaName}."SELECTLIST"."MODIFIEDDATETIME" IS 'When (date and time) the record was last modified';
COMMENT ON COLUMN ${schemaName}."SELECTLIST"."NAME" IS 'Name of the list - used as a handle to the list in the tag library';
COMMENT ON COLUMN ${schemaName}."SELECTLIST"."DESCRIPTION" IS 'Description of the list';


CREATE TABLE ${schemaName}."SELECTLISTOPTION"
( "ID" NUMBER NOT NULL CONSTRAINT "SELECTLISTOPTION_PK" PRIMARY KEY
, "CREATEDUSERID" VARCHAR2(64) NOT NULL
, "CREATEDDATETIME" DATE NOT NULL
, "MODIFIEDUSERID" VARCHAR2(64)
, "MODIFIEDDATETIME" DATE
, "SELECTLISTID" NUMBER(38) NOT NULL
, "VALUE" VARCHAR2(64) NOT NULL
, "DISPLAYORDER" NUMBER NOT NULL
, CONSTRAINT "SELECTLISTOPTION_FK1" FOREIGN KEY ("SELECTLISTID") REFERENCES ${schemaName}."SELECTLIST"("ID")
, CONSTRAINT "SELECTLISTOPTION_UK1" UNIQUE ("SELECTLISTID", "VALUE")
, CONSTRAINT "SELECTLISTOPTION_UK2" UNIQUE ("SELECTLISTID", "DISPLAYORDER")
)
TABLESPACE ${tableTablespace}
;

CREATE INDEX ${schemaName}."SELECTLISTOPTION_IDX1"
ON ${schemaName}."SELECTLISTOPTION"
("SELECTLISTID")
TABLESPACE ${indexTablespace}
;

CREATE SEQUENCE ${schemaName}."SELECTLISTOPTION_SEQ";

COMMENT ON TABLE ${schemaName}."SELECTLISTOPTION" IS 'HTML option item data';
COMMENT ON COLUMN ${schemaName}."SELECTLISTOPTION"."ID" IS 'Surrogate primary key - generated from SELECTLISTOPTION_SEQ sequence';
COMMENT ON COLUMN ${schemaName}."SELECTLISTOPTION"."CREATEDUSERID" IS 'Who created the record';
COMMENT ON COLUMN ${schemaName}."SELECTLISTOPTION"."CREATEDDATETIME" IS 'When (date and time) the record was created';
COMMENT ON COLUMN ${schemaName}."SELECTLISTOPTION"."MODIFIEDUSERID" IS 'Who last modified the record';
COMMENT ON COLUMN ${schemaName}."SELECTLISTOPTION"."MODIFIEDDATETIME" IS 'When (date and time) the record was last modified';
COMMENT ON COLUMN ${schemaName}."SELECTLISTOPTION"."SELECTLISTID" IS 'Reference to SELECTLIST';
COMMENT ON COLUMN ${schemaName}."SELECTLISTOPTION"."VALUE" IS 'VALUE attribute of HTML option tag - will be saved table using the select list';
COMMENT ON COLUMN ${schemaName}."SELECTLISTOPTION"."DISPLAYORDER" IS 'Orders the displayed list items';
