--liquibase formatted sql

--changeset Novacroft:11.0.82
CREATE TABLE ${schemaName}.ALTERNATIVEZONEMAPPING
( "ID" NUMBER(38) NOT NULL CONSTRAINT ALTERNATIVEZONEMAPPING_PK PRIMARY KEY
, "CREATEDUSERID" VARCHAR2(64) NOT NULL
, "CREATEDDATETIME" DATE NOT NULL
, "MODIFIEDUSERID" VARCHAR2(64)
, "MODIFIEDDATETIME" DATE
, "STARTZONE" NUMBER(2)
, "ENDZONE" NUMBER(2)
, "ALTERNATIVESTARTZONE" NUMBER(2)
, "ALTERNATIVEENDZONE" NUMBER(2)
, CONSTRAINT "ALTERNATIVEZONEMAPPING_UK1" UNIQUE ("STARTZONE", "ENDZONE")
)
TABLESPACE ${tableTablespace}
;

CREATE SEQUENCE ${schemaName}.ALTERNATIVEZONEMAPPING_SEQ START WITH 1 INCREMENT BY 1 NOMAXVALUE;

COMMENT ON TABLE ${schemaName}.ALTERNATIVEZONEMAPPING IS 'Provide alternative zone mapping for user selected zone mappings not existed';
COMMENT ON COLUMN ${schemaName}.ALTERNATIVEZONEMAPPING."ID" IS 'Surrogate primary key - generated from ALTERNATIVEZONEMAPPING_SEQ sequence';
COMMENT ON COLUMN ${schemaName}.ALTERNATIVEZONEMAPPING."CREATEDUSERID" IS 'Who created the record';
COMMENT ON COLUMN ${schemaName}.ALTERNATIVEZONEMAPPING."CREATEDDATETIME" IS 'When (date and time) the record was created';
COMMENT ON COLUMN ${schemaName}.ALTERNATIVEZONEMAPPING."MODIFIEDUSERID" IS 'Who last modified the record';
COMMENT ON COLUMN ${schemaName}.ALTERNATIVEZONEMAPPING."MODIFIEDDATETIME" IS 'When (date and time) the record was last modified';
COMMENT ON COLUMN ${schemaName}.ALTERNATIVEZONEMAPPING."STARTZONE" IS 'Start zone of the travelcard';
COMMENT ON COLUMN ${schemaName}.ALTERNATIVEZONEMAPPING."ENDZONE" IS 'End zone of the travelcard';
COMMENT ON COLUMN ${schemaName}.ALTERNATIVEZONEMAPPING."ALTERNATIVESTARTZONE" IS 'Alternative start zone of the travelcard';
COMMENT ON COLUMN ${schemaName}.ALTERNATIVEZONEMAPPING."ALTERNATIVEENDZONE" IS 'Alternative end zone of the travelcard';

