--liquibase formatted sql

--changeset Novacroft:11.0.164

-- Rules for team and Organisation
INSERT INTO ${schemaName}."RANDOMAPPROVALSAMPLE"
("ID", "CREATEDUSERID", "CREATEDDATETIME", "MODIFIEDUSERID", "MODIFIEDDATETIME", "ORGANISATION", "DEPARTMENT", "TEAM", "SCENARIO", "BASIS", "MINVALUETHRESHOLD", "MAXVALUETHRESHOLD", "PERCENTAGETOAPPROVE", "RULETYPE" )
VALUES
(${schemaName}."RANDOMAPPROVALSAMPLE_SEQ".nextval, 'Installer', SYSDATE, NULL, NULL, 'ORGX', 'OYSTER', 'TEAMX', 'GOODWILL', NULL, 0, 1500, 5, 'RANDOM_APPROVAL_SAMPLE_RULE');

INSERT INTO ${schemaName}."RANDOMAPPROVALSAMPLE"
("ID", "CREATEDUSERID", "CREATEDDATETIME", "MODIFIEDUSERID", "MODIFIEDDATETIME", "ORGANISATION", "DEPARTMENT", "TEAM", "SCENARIO", "BASIS", "MINVALUETHRESHOLD", "MAXVALUETHRESHOLD", "PERCENTAGETOAPPROVE", "RULETYPE")
VALUES
(${schemaName}."RANDOMAPPROVALSAMPLE_SEQ".nextval, 'Installer', SYSDATE, NULL, NULL, 'ORGX', 'OYSTER', 'TEAMX', 'OTHER', NULL, 1, 5000, 5, 'RANDOM_APPROVAL_SAMPLE_RULE');

INSERT INTO ${schemaName}."RANDOMAPPROVALSAMPLE"
("ID", "CREATEDUSERID", "CREATEDDATETIME", "MODIFIEDUSERID", "MODIFIEDDATETIME", "ORGANISATION", "DEPARTMENT", "TEAM", "SCENARIO", "BASIS", "MINVALUETHRESHOLD", "MAXVALUETHRESHOLD", "PERCENTAGETOAPPROVE", "RULETYPE")
VALUES
(${schemaName}."RANDOMAPPROVALSAMPLE_SEQ".nextval, 'Installer', SYSDATE, NULL, NULL, 'ORGX', 'OYSTER', 'TEAMX', 'OTHER', NULL, 5001, 12500, 10, 'RANDOM_APPROVAL_SAMPLE_RULE');

INSERT INTO ${schemaName}."RANDOMAPPROVALSAMPLE"
("ID", "CREATEDUSERID", "CREATEDDATETIME", "MODIFIEDUSERID", "MODIFIEDDATETIME", "ORGANISATION", "DEPARTMENT", "TEAM", "SCENARIO", "BASIS", "MINVALUETHRESHOLD", "MAXVALUETHRESHOLD", "PERCENTAGETOAPPROVE", "RULETYPE")
VALUES
(${schemaName}."RANDOMAPPROVALSAMPLE_SEQ".nextval, 'Installer', SYSDATE, NULL, NULL, 'ORGX', 'LU', 'TEAMX', 'GOODWILL', NULL, NULL, NULL, 5, 'RANDOM_APPROVAL_SAMPLE_RULE');

INSERT INTO ${schemaName}."RANDOMAPPROVALSAMPLE"
("ID", "CREATEDUSERID", "CREATEDDATETIME", "MODIFIEDUSERID", "MODIFIEDDATETIME", "ORGANISATION", "DEPARTMENT", "TEAM", "SCENARIO", "BASIS", "MINVALUETHRESHOLD", "MAXVALUETHRESHOLD", "PERCENTAGETOAPPROVE", "RULETYPE")
VALUES
(${schemaName}."RANDOMAPPROVALSAMPLE_SEQ".nextval, 'Installer', SYSDATE, NULL, NULL, 'ORGX', 'OYSTER', 'TEAMX', NULL, 'SPECIAL', NULL, NULL, 100, 'RANDOM_APPROVAL_SAMPLE_RULE');

INSERT INTO ${schemaName}."RANDOMAPPROVALSAMPLE"
("ID", "CREATEDUSERID", "CREATEDDATETIME", "MODIFIEDUSERID", "MODIFIEDDATETIME", "ORGANISATION", "DEPARTMENT", "TEAM", "SCENARIO", "BASIS", "MINVALUETHRESHOLD", "MAXVALUETHRESHOLD", "PERCENTAGETOAPPROVE", "RULETYPE")
VALUES
(${schemaName}."RANDOMAPPROVALSAMPLE_SEQ".nextval, 'Installer', SYSDATE, NULL, NULL, 'ORGX', 'CCS', 'TEAMX', 'GOODWILL', NULL, NULL, NULL, 5, 'RANDOM_APPROVAL_SAMPLE_RULE');
-- Rules For Organisation (no team)
INSERT INTO ${schemaName}."RANDOMAPPROVALSAMPLE"
("ID", "CREATEDUSERID", "CREATEDDATETIME", "MODIFIEDUSERID", "MODIFIEDDATETIME", "ORGANISATION", "DEPARTMENT", "TEAM", "SCENARIO", "BASIS", "MINVALUETHRESHOLD", "MAXVALUETHRESHOLD", "PERCENTAGETOAPPROVE", "RULETYPE" )
VALUES
(${schemaName}."RANDOMAPPROVALSAMPLE_SEQ".nextval, 'Installer', SYSDATE, NULL, NULL, 'ORGX', 'OYSTER', 'DEFAULT', 'GOODWILL', NULL, 0, 1500, 5, 'RANDOM_APPROVAL_SAMPLE_RULE');

INSERT INTO ${schemaName}."RANDOMAPPROVALSAMPLE"
("ID", "CREATEDUSERID", "CREATEDDATETIME", "MODIFIEDUSERID", "MODIFIEDDATETIME", "ORGANISATION", "DEPARTMENT", "TEAM", "SCENARIO", "BASIS", "MINVALUETHRESHOLD", "MAXVALUETHRESHOLD", "PERCENTAGETOAPPROVE", "RULETYPE")
VALUES
(${schemaName}."RANDOMAPPROVALSAMPLE_SEQ".nextval, 'Installer', SYSDATE, NULL, NULL, 'ORGX', 'OYSTER', 'DEFAULT', 'OTHER', NULL, 1, 5000, 5, 'RANDOM_APPROVAL_SAMPLE_RULE');

INSERT INTO ${schemaName}."RANDOMAPPROVALSAMPLE"
("ID", "CREATEDUSERID", "CREATEDDATETIME", "MODIFIEDUSERID", "MODIFIEDDATETIME", "ORGANISATION", "DEPARTMENT", "TEAM", "SCENARIO", "BASIS", "MINVALUETHRESHOLD", "MAXVALUETHRESHOLD", "PERCENTAGETOAPPROVE", "RULETYPE")
VALUES
(${schemaName}."RANDOMAPPROVALSAMPLE_SEQ".nextval, 'Installer', SYSDATE, NULL, NULL, 'ORGX', 'OYSTER', 'DEFAULT', 'OTHER', NULL, 5001, 12500, 10, 'RANDOM_APPROVAL_SAMPLE_RULE');

INSERT INTO ${schemaName}."RANDOMAPPROVALSAMPLE"
("ID", "CREATEDUSERID", "CREATEDDATETIME", "MODIFIEDUSERID", "MODIFIEDDATETIME", "ORGANISATION", "DEPARTMENT", "TEAM", "SCENARIO", "BASIS", "MINVALUETHRESHOLD", "MAXVALUETHRESHOLD", "PERCENTAGETOAPPROVE", "RULETYPE")
VALUES
(${schemaName}."RANDOMAPPROVALSAMPLE_SEQ".nextval, 'Installer', SYSDATE, NULL, NULL, 'ORGX', 'LU', 'DEFAULT', 'GOODWILL', NULL, NULL, NULL, 5, 'RANDOM_APPROVAL_SAMPLE_RULE');

INSERT INTO ${schemaName}."RANDOMAPPROVALSAMPLE"
("ID", "CREATEDUSERID", "CREATEDDATETIME", "MODIFIEDUSERID", "MODIFIEDDATETIME", "ORGANISATION", "DEPARTMENT", "TEAM", "SCENARIO", "BASIS", "MINVALUETHRESHOLD", "MAXVALUETHRESHOLD", "PERCENTAGETOAPPROVE", "RULETYPE")
VALUES
(${schemaName}."RANDOMAPPROVALSAMPLE_SEQ".nextval, 'Installer', SYSDATE, NULL, NULL, 'ORGX', 'OYSTER', 'DEFAULT', NULL, 'SPECIAL', NULL, NULL, 100, 'RANDOM_APPROVAL_SAMPLE_RULE');

INSERT INTO ${schemaName}."RANDOMAPPROVALSAMPLE"
("ID", "CREATEDUSERID", "CREATEDDATETIME", "MODIFIEDUSERID", "MODIFIEDDATETIME", "ORGANISATION", "DEPARTMENT", "TEAM", "SCENARIO", "BASIS", "MINVALUETHRESHOLD", "MAXVALUETHRESHOLD", "PERCENTAGETOAPPROVE", "RULETYPE")
VALUES
(${schemaName}."RANDOMAPPROVALSAMPLE_SEQ".nextval, 'Installer', SYSDATE, NULL, NULL, 'ORGX', 'CCS', 'DEFAULT', 'GOODWILL', NULL, NULL, NULL, 5, 'RANDOM_APPROVAL_SAMPLE_RULE');

--Rules For No team + No orgainsation (default rules)
INSERT INTO ${schemaName}."RANDOMAPPROVALSAMPLE"
("ID", "CREATEDUSERID", "CREATEDDATETIME", "MODIFIEDUSERID", "MODIFIEDDATETIME", "ORGANISATION", "DEPARTMENT", "TEAM", "SCENARIO", "BASIS", "MINVALUETHRESHOLD", "MAXVALUETHRESHOLD", "PERCENTAGETOAPPROVE", "RULETYPE" )
VALUES
(${schemaName}."RANDOMAPPROVALSAMPLE_SEQ".nextval, 'Installer', SYSDATE, NULL, NULL, 'DEFAULT', 'OYSTER', 'DEFAULT', 'GOODWILL', NULL, 0, 1500, 5, 'RANDOM_APPROVAL_SAMPLE_RULE');

INSERT INTO ${schemaName}."RANDOMAPPROVALSAMPLE"
("ID", "CREATEDUSERID", "CREATEDDATETIME", "MODIFIEDUSERID", "MODIFIEDDATETIME", "ORGANISATION", "DEPARTMENT", "TEAM", "SCENARIO", "BASIS", "MINVALUETHRESHOLD", "MAXVALUETHRESHOLD", "PERCENTAGETOAPPROVE", "RULETYPE")
VALUES
(${schemaName}."RANDOMAPPROVALSAMPLE_SEQ".nextval, 'Installer', SYSDATE, NULL, NULL, 'DEFAULT', 'OYSTER', 'DEFAULT', 'OTHER', NULL, 1, 5000, 5, 'RANDOM_APPROVAL_SAMPLE_RULE');

INSERT INTO ${schemaName}."RANDOMAPPROVALSAMPLE"
("ID", "CREATEDUSERID", "CREATEDDATETIME", "MODIFIEDUSERID", "MODIFIEDDATETIME", "ORGANISATION", "DEPARTMENT", "TEAM", "SCENARIO", "BASIS", "MINVALUETHRESHOLD", "MAXVALUETHRESHOLD", "PERCENTAGETOAPPROVE", "RULETYPE")
VALUES
(${schemaName}."RANDOMAPPROVALSAMPLE_SEQ".nextval, 'Installer', SYSDATE, NULL, NULL, 'DEFAULT', 'OYSTER', 'DEFAULT', 'OTHER', NULL, 5001, 12500, 10, 'RANDOM_APPROVAL_SAMPLE_RULE');

INSERT INTO ${schemaName}."RANDOMAPPROVALSAMPLE"
("ID", "CREATEDUSERID", "CREATEDDATETIME", "MODIFIEDUSERID", "MODIFIEDDATETIME", "ORGANISATION", "DEPARTMENT", "TEAM", "SCENARIO", "BASIS", "MINVALUETHRESHOLD", "MAXVALUETHRESHOLD", "PERCENTAGETOAPPROVE", "RULETYPE")
VALUES
(${schemaName}."RANDOMAPPROVALSAMPLE_SEQ".nextval, 'Installer', SYSDATE, NULL, NULL, 'DEFAULT', 'LU', 'DEFAULT', 'GOODWILL', NULL, NULL, NULL, 5, 'RANDOM_APPROVAL_SAMPLE_RULE');

INSERT INTO ${schemaName}."RANDOMAPPROVALSAMPLE"
("ID", "CREATEDUSERID", "CREATEDDATETIME", "MODIFIEDUSERID", "MODIFIEDDATETIME", "ORGANISATION", "DEPARTMENT", "TEAM", "SCENARIO", "BASIS", "MINVALUETHRESHOLD", "MAXVALUETHRESHOLD", "PERCENTAGETOAPPROVE", "RULETYPE")
VALUES
(${schemaName}."RANDOMAPPROVALSAMPLE_SEQ".nextval, 'Installer', SYSDATE, NULL, NULL, 'DEFAULT', 'OYSTER', 'DEFAULT', NULL, 'SPECIAL', NULL, NULL, 100, 'RANDOM_APPROVAL_SAMPLE_RULE');

INSERT INTO ${schemaName}."RANDOMAPPROVALSAMPLE"
("ID", "CREATEDUSERID", "CREATEDDATETIME", "MODIFIEDUSERID", "MODIFIEDDATETIME", "ORGANISATION", "DEPARTMENT", "TEAM", "SCENARIO", "BASIS", "MINVALUETHRESHOLD", "MAXVALUETHRESHOLD", "PERCENTAGETOAPPROVE", "RULETYPE")
VALUES
(${schemaName}."RANDOMAPPROVALSAMPLE_SEQ".nextval, 'Installer', SYSDATE, NULL, NULL, 'DEFAULT', 'CCS', 'DEFAULT', 'GOODWILL', NULL, NULL, NULL, 5, 'RANDOM_APPROVAL_SAMPLE_RULE');

INSERT INTO ${schemaName}."CLAIMLIMITTHRESHOLD"
("ID", "CREATEDUSERID", "CREATEDDATETIME", "MODIFIEDUSERID", "MODIFIEDDATETIME", "DEPARTMENT", "SCENARIO", "INSTANCETHRESHOLD", "RULETYPE" )
VALUES
(${schemaName}."CLAIMLIMITTHRESHOLD_SEQ".nextval, 'Installer', SYSDATE, NULL, NULL, 'RCL', 'FAILEDCARD', 3, 'REPEAT_CLAIM_LIMIT_RULE');

INSERT INTO ${schemaName}."CLAIMLIMITTHRESHOLD"
("ID", "CREATEDUSERID", "CREATEDDATETIME", "MODIFIEDUSERID", "MODIFIEDDATETIME", "DEPARTMENT", "SCENARIO", "INSTANCETHRESHOLD", "RULETYPE" )
VALUES
(${schemaName}."CLAIMLIMITTHRESHOLD_SEQ".nextval, 'Installer', SYSDATE, NULL, NULL, 'RCL', 'LOST', 3, 'REPEAT_CLAIM_LIMIT_RULE');

INSERT INTO ${schemaName}."CLAIMLIMITTHRESHOLD"
("ID", "CREATEDUSERID", "CREATEDDATETIME", "MODIFIEDUSERID", "MODIFIEDDATETIME", "DEPARTMENT", "SCENARIO", "INSTANCETHRESHOLD", "RULETYPE" )
VALUES
(${schemaName}."CLAIMLIMITTHRESHOLD_SEQ".nextval, 'Installer', SYSDATE, NULL, NULL, 'RCL', 'STOLEN', 3, 'REPEAT_CLAIM_LIMIT_RULE');

INSERT INTO ${schemaName}."CLAIMLIMITTHRESHOLD"
("ID", "CREATEDUSERID", "CREATEDDATETIME", "MODIFIEDUSERID", "MODIFIEDDATETIME", "DEPARTMENT", "SCENARIO", "INSTANCETHRESHOLD", "RULETYPE" )
VALUES
(${schemaName}."CLAIMLIMITTHRESHOLD_SEQ".nextval, 'Installer', SYSDATE, NULL, NULL, 'RCL', 'DESTROYED', 3, 'REPEAT_CLAIM_LIMIT_RULE');

INSERT INTO ${schemaName}."CLAIMLIMITTHRESHOLD"
("ID", "CREATEDUSERID", "CREATEDDATETIME", "MODIFIEDUSERID", "MODIFIEDDATETIME", "DEPARTMENT", "SCENARIO", "INSTANCETHRESHOLD", "RULETYPE" )
VALUES
(${schemaName}."CLAIMLIMITTHRESHOLD_SEQ".nextval, 'Installer', SYSDATE, NULL, NULL, 'RCL', 'OVERLAP', 2, 'REPEAT_CLAIM_LIMIT_RULE');

INSERT INTO ${schemaName}."CLAIMLIMITTHRESHOLD"
("ID", "CREATEDUSERID", "CREATEDDATETIME", "MODIFIEDUSERID", "MODIFIEDDATETIME", "DEPARTMENT", "SCENARIO", "INSTANCETHRESHOLD", "RULETYPE" )
VALUES
(${schemaName}."CLAIMLIMITTHRESHOLD_SEQ".nextval, 'Installer', SYSDATE, NULL, NULL, 'GOODWILL', 'SEASONTCKTLEFTATHOME', 2, 'REPEAT_CLAIM_LIMIT_RULE');

INSERT INTO ${schemaName}."CLAIMLIMITTHRESHOLD"
("ID", "CREATEDUSERID", "CREATEDDATETIME", "MODIFIEDUSERID", "MODIFIEDDATETIME", "DEPARTMENT", "SCENARIO", "INSTANCETHRESHOLD", "RULETYPE" )
VALUES
(${schemaName}."CLAIMLIMITTHRESHOLD_SEQ".nextval, 'Installer', SYSDATE, NULL, NULL, 'GOODWILL', 'SEASONTCKTNOTLEFTATHOME', 6, 'REPEAT_CLAIM_LIMIT_RULE');

INSERT INTO ${schemaName}."CLAIMLIMITTHRESHOLD"
("ID", "CREATEDUSERID", "CREATEDDATETIME", "MODIFIEDUSERID", "MODIFIEDDATETIME", "DEPARTMENT", "SCENARIO", "MINVALUETHRESHOLD", "RULETYPE" )
VALUES
(${schemaName}."CLAIMLIMITTHRESHOLD_SEQ".nextval, 'Installer', SYSDATE, NULL, NULL, 'GOODWILL', 'SEASONTCKTNOTLEFTATHOME', 15000, 'REPEAT_CLAIM_LIMIT_RULE');

INSERT INTO ${schemaName}."CLAIMLIMITTHRESHOLD"
("ID", "CREATEDUSERID", "CREATEDDATETIME", "MODIFIEDUSERID", "MODIFIEDDATETIME", "DEPARTMENT", "SCENARIO", "INSTANCETHRESHOLD", "RULETYPE" )
VALUES
(${schemaName}."CLAIMLIMITTHRESHOLD_SEQ".nextval, 'Installer', SYSDATE, NULL, NULL, 'CANCEL_AND_SURRENDER', 'CANCEL_AND_SURRENDER', 3, 'REPEAT_CLAIM_LIMIT_RULE');
