--liquibase formatted sql

--changeset Novacroft:11.0.64
CREATE TABLE ${schemaName}.calltype
("ID" NUMBER NOT NULL CONSTRAINT calltype_pk PRIMARY KEY
, "CREATEDUSERID" VARCHAR2(64) NOT NULL
, "CREATEDDATETIME" DATE NOT NULL
, "MODIFIEDUSERID" VARCHAR2(64)
, "MODIFIEDDATETIME" DATE
, "DESCRIPTION" VARCHAR2(80)
, "ACTIVE" NUMBER
) TABLESPACE ${tableTablespace};

CREATE SEQUENCE ${schemaName}.calltype_seq START WITH 1 INCREMENT BY 1 NOMAXVALUE;

COMMENT ON TABLE ${schemaName}.calltype IS 'Calltype';
COMMENT ON COLUMN ${schemaName}.calltype."ID" IS 'Surrogate primary key - generated from calltype_SEQ sequence';
COMMENT ON COLUMN ${schemaName}.calltype."CREATEDUSERID" IS 'Who created the record';
COMMENT ON COLUMN ${schemaName}.calltype."CREATEDDATETIME" IS 'When (date and time) the record was created';
COMMENT ON COLUMN ${schemaName}.calltype."MODIFIEDUSERID" IS 'Who last modified the record';
COMMENT ON COLUMN ${schemaName}.calltype."MODIFIEDDATETIME" IS 'When (date and time) the record was last modified';
COMMENT ON COLUMN ${schemaName}.calltype."DESCRIPTION" IS 'Description';
COMMENT ON COLUMN ${schemaName}.calltype."ACTIVE" IS 'Active';

CREATE TABLE ${schemaName}.call
( "ID" NUMBER(38) NOT NULL CONSTRAINT call_pk PRIMARY KEY
, "CREATEDUSERID" VARCHAR2(64) NOT NULL
, "CREATEDDATETIME" DATE NOT NULL
, "MODIFIEDUSERID" VARCHAR2(64)
, "MODIFIEDDATETIME" DATE
, "TITLE" VARCHAR2(10)
, "FIRSTNAME" VARCHAR2(50)
, "LASTNAME" VARCHAR2(50)
, "HOMEPHONE" VARCHAR2(50)
, "MOBILEPHONE" VARCHAR2(50)
, "EMAILADDRESS" VARCHAR2(100)
, "ADDRESSID" NUMBER(38)
, "CALLTYPEID" NUMBER
, "DESCRIPTION" CLOB
, "RESOLUTION" CLOB
, "NOTES" CLOB
, "ANONYMISED" NUMBER(1) DEFAULT 0 NOT NULL
, "READONLY" NUMBER(1) DEFAULT 0 NOT NULL
, CONSTRAINT call_fk1 FOREIGN KEY ("ADDRESSID") REFERENCES ${schemaName}.address("ID")
, CONSTRAINT call_fk2 FOREIGN KEY ("CALLTYPEID") REFERENCES ${schemaName}.calltype("ID")
)
TABLESPACE ${tableTablespace}
;

CREATE INDEX ${schemaName}.call_idx1
ON ${schemaName}.call
( "CREATEDDATETIME")
TABLESPACE ${indexTablespace}
;

CREATE SEQUENCE ${schemaName}.call_seq START WITH 1 INCREMENT BY 1 NOMAXVALUE;

COMMENT ON TABLE ${schemaName}.call IS 'Call';
COMMENT ON COLUMN ${schemaName}.call."ID" IS 'Surrogate primary key - generated from CALL_SEQ sequence';
COMMENT ON COLUMN ${schemaName}.call."CREATEDUSERID" IS 'Who created the record';
COMMENT ON COLUMN ${schemaName}.call."CREATEDDATETIME" IS 'When (date and time) the record was created';
COMMENT ON COLUMN ${schemaName}.call."MODIFIEDUSERID" IS 'Who last modified the record';
COMMENT ON COLUMN ${schemaName}.call."MODIFIEDDATETIME" IS 'When (date and time) the record was last modified';
COMMENT ON COLUMN ${schemaName}.call."TITLE" IS 'Title';
COMMENT ON COLUMN ${schemaName}.call."FIRSTNAME" IS 'First name';
COMMENT ON COLUMN ${schemaName}.call."LASTNAME" IS 'Last Name';
COMMENT ON COLUMN ${schemaName}.call."HOMEPHONE" IS 'Telephone number';
COMMENT ON COLUMN ${schemaName}.call."MOBILEPHONE" IS 'Mobile number';
COMMENT ON COLUMN ${schemaName}.call."EMAILADDRESS" IS 'Email address';
COMMENT ON COLUMN ${schemaName}.call."ANONYMISED" IS 'TBA flag: 0 = false; 1 = true';
COMMENT ON COLUMN ${schemaName}.call."READONLY" IS 'TBA flag: 0 = false; 1 = true';
COMMENT ON COLUMN ${schemaName}.call."ADDRESSID" IS 'Reference to Address';

CREATE TABLE ${schemaName}.call_AUD
( "REV" NUMBER NOT NULL
, "REVTYPE" NUMBER NOT NULL
,"ID" NUMBER(38) NOT NULL
, "CREATEDUSERID" VARCHAR2(64)
, "CREATEDDATETIME" DATE
, "MODIFIEDUSERID" VARCHAR2(64)
, "MODIFIEDDATETIME" DATE
, "TITLE" VARCHAR2(10)
, "FIRSTNAME" VARCHAR2(50)
, "LASTNAME" VARCHAR2(50)
, "HOMEPHONE" VARCHAR2(50)
, "MOBILEPHONE" VARCHAR2(50)
, "EMAILADDRESS" VARCHAR2(100)
, "ADDRESSID" NUMBER(38)
, "CALLTYPEID" VARCHAR2(10)
, "DESCRIPTION" CLOB
, "RESOLUTION" CLOB
, "NOTES" CLOB
, "ANONYMISED" NUMBER(1)
, "READONLY" NUMBER(1)
) TABLESPACE ${tableTablespace}
;

INSERT INTO CALLTYPE (ID, CREATEDUSERID, CREATEDDATETIME, MODIFIEDUSERID, MODIFIEDDATETIME, DESCRIPTION, ACTIVE)
VALUES (CALLTYPE_SEQ.NEXTVAL, 'Installer', sysdate, NULL, NULL, 'New look TfL website enquiry', 1);
INSERT INTO CALLTYPE (ID, CREATEDUSERID, CREATEDDATETIME, MODIFIEDUSERID, MODIFIEDDATETIME, DESCRIPTION, ACTIVE)
VALUES (CALLTYPE_SEQ.NEXTVAL, 'Installer', sysdate, NULL, NULL, 'Damaged Card Query', 1);
INSERT INTO CALLTYPE (ID, CREATEDUSERID, CREATEDDATETIME, MODIFIEDUSERID, MODIFIEDDATETIME, DESCRIPTION, ACTIVE)
VALUES (CALLTYPE_SEQ.NEXTVAL, 'Installer', sysdate, NULL, NULL, q'$Where's my card - Applied But Not Received$', 1);
INSERT INTO CALLTYPE (ID, CREATEDUSERID, CREATEDDATETIME, MODIFIEDUSERID, MODIFIEDDATETIME, DESCRIPTION, ACTIVE)
VALUES (CALLTYPE_SEQ.NEXTVAL, 'Installer', sysdate, NULL, NULL, 'Bus/Tube Problems', 1);
INSERT INTO CALLTYPE (ID, CREATEDUSERID, CREATEDDATETIME, MODIFIEDUSERID, MODIFIEDDATETIME, DESCRIPTION, ACTIVE)
VALUES (CALLTYPE_SEQ.NEXTVAL, 'Installer', sysdate, NULL, NULL, 'Call From TfL', 1);
INSERT INTO CALLTYPE (ID, CREATEDUSERID, CREATEDDATETIME, MODIFIEDUSERID, MODIFIEDDATETIME, DESCRIPTION, ACTIVE)
VALUES (CALLTYPE_SEQ.NEXTVAL, 'Installer', sysdate, NULL, NULL, 'General Enquiry', 1);
INSERT INTO CALLTYPE (ID, CREATEDUSERID, CREATEDDATETIME, MODIFIEDUSERID, MODIFIEDDATETIME, DESCRIPTION, ACTIVE)
VALUES (CALLTYPE_SEQ.NEXTVAL, 'Installer', sysdate, NULL, NULL, 'Mail Received', 1);
INSERT INTO CALLTYPE (ID, CREATEDUSERID, CREATEDDATETIME, MODIFIEDUSERID, MODIFIEDDATETIME, DESCRIPTION, ACTIVE)
VALUES (CALLTYPE_SEQ.NEXTVAL, 'Installer', sysdate, NULL, NULL, 'Mail Sent', 1);
INSERT INTO CALLTYPE (ID, CREATEDUSERID, CREATEDDATETIME, MODIFIEDUSERID, MODIFIEDDATETIME, DESCRIPTION, ACTIVE)
VALUES (CALLTYPE_SEQ.NEXTVAL, 'Installer', sysdate, NULL, NULL, 'Oyster Card', 1);
INSERT INTO CALLTYPE (ID, CREATEDUSERID, CREATEDDATETIME, MODIFIEDUSERID, MODIFIEDDATETIME, DESCRIPTION, ACTIVE)
VALUES (CALLTYPE_SEQ.NEXTVAL, 'Installer', sysdate, NULL, NULL, 'Other', 1);
INSERT INTO CALLTYPE (ID, CREATEDUSERID, CREATEDDATETIME, MODIFIEDUSERID, MODIFIEDDATETIME, DESCRIPTION, ACTIVE)
VALUES (CALLTYPE_SEQ.NEXTVAL, 'Installer', sysdate, NULL, NULL, 'Rejected Enquiry', 1);
INSERT INTO CALLTYPE (ID, CREATEDUSERID, CREATEDDATETIME, MODIFIEDUSERID, MODIFIEDDATETIME, DESCRIPTION, ACTIVE)
VALUES (CALLTYPE_SEQ.NEXTVAL, 'Installer', sysdate, NULL, NULL, 'Supervisor', 1);
INSERT INTO CALLTYPE (ID, CREATEDUSERID, CREATEDDATETIME, MODIFIEDUSERID, MODIFIEDDATETIME, DESCRIPTION, ACTIVE)
VALUES (CALLTYPE_SEQ.NEXTVAL, 'Installer', sysdate, NULL, NULL, 'Travel Card Enquiries', 1);
INSERT INTO CALLTYPE (ID, CREATEDUSERID, CREATEDDATETIME, MODIFIEDUSERID, MODIFIEDDATETIME, DESCRIPTION, ACTIVE)
VALUES (CALLTYPE_SEQ.NEXTVAL, 'Installer', sysdate, NULL, NULL, 'Call To TfL', 1);
INSERT INTO CALLTYPE (ID, CREATEDUSERID, CREATEDDATETIME, MODIFIEDUSERID, MODIFIEDDATETIME, DESCRIPTION, ACTIVE)
VALUES (CALLTYPE_SEQ.NEXTVAL, 'Installer', sysdate, NULL, NULL, 'Misdirected Call', 1);
INSERT INTO CALLTYPE (ID, CREATEDUSERID, CREATEDDATETIME, MODIFIEDUSERID, MODIFIEDDATETIME, DESCRIPTION, ACTIVE)
VALUES (CALLTYPE_SEQ.NEXTVAL, 'Installer', sysdate, NULL, NULL, 'Lost Card Query', 1);
INSERT INTO CALLTYPE (ID, CREATEDUSERID, CREATEDDATETIME, MODIFIEDUSERID, MODIFIEDDATETIME, DESCRIPTION, ACTIVE)
VALUES (CALLTYPE_SEQ.NEXTVAL, 'Installer', sysdate, NULL, NULL, 'Stolen Card Query', 1);
INSERT INTO CALLTYPE (ID, CREATEDUSERID, CREATEDDATETIME, MODIFIEDUSERID, MODIFIEDDATETIME, DESCRIPTION, ACTIVE)
VALUES (CALLTYPE_SEQ.NEXTVAL, 'Installer', sysdate, NULL, NULL, 'Failed Card Query', 1);
INSERT INTO CALLTYPE (ID, CREATEDUSERID, CREATEDDATETIME, MODIFIEDUSERID, MODIFIEDDATETIME, DESCRIPTION, ACTIVE)
VALUES (CALLTYPE_SEQ.NEXTVAL, 'Installer', sysdate, NULL, NULL, 'Refund Query', 1);

