--liquibase formatted sql

--changeset Novacroft:11.0.142
INSERT INTO ${schemaName}.ADMINISTRATIONFEE
( "ID", "CREATEDUSERID", "CREATEDDATETIME", "MODIFIEDUSERID", "MODIFIEDDATETIME","TYPE", "PRICE")
VALUES
(${schemaName}.ADMINISTRATIONFEE_SEQ.nextval, 'Installer', SYSDATE, NULL, NULL, 'administrationFeeFailedCardRefund', '0');

INSERT INTO ${schemaName}.ADMINISTRATIONFEE
( "ID", "CREATEDUSERID", "CREATEDDATETIME", "MODIFIEDUSERID", "MODIFIEDDATETIME","TYPE", "PRICE")
VALUES
(${schemaName}.ADMINISTRATIONFEE_SEQ.nextval, 'Installer', SYSDATE, NULL, NULL, 'administrationFeeLostRefund', '500');

INSERT INTO ${schemaName}.ADMINISTRATIONFEE
( "ID", "CREATEDUSERID", "CREATEDDATETIME", "MODIFIEDUSERID", "MODIFIEDDATETIME","TYPE", "PRICE")
VALUES
(${schemaName}.ADMINISTRATIONFEE_SEQ.nextval, 'Installer', SYSDATE, NULL, NULL, 'administrationFeeStolenRefund', '500');

INSERT INTO ${schemaName}.ADMINISTRATIONFEE
( "ID", "CREATEDUSERID", "CREATEDDATETIME", "MODIFIEDUSERID", "MODIFIEDDATETIME","TYPE", "PRICE")
VALUES
(${schemaName}.ADMINISTRATIONFEE_SEQ.nextval, 'Installer', SYSDATE, NULL, NULL, 'administrationFeeCancelAndSurrenderRefund', '400');