--liquibase formatted sql

--changeset Novacroft:11.0.72
CREATE TABLE ${schemaName}."SHIPPINGMETHOD"
("ID" NUMBER(38) NOT NULL CONSTRAINT "SHIPPINGMETHOD_PK" PRIMARY KEY
, "CREATEDUSERID" VARCHAR2(64) NOT NULL
, "CREATEDDATETIME" DATE NOT NULL
, "MODIFIEDUSERID" VARCHAR2(64)
, "MODIFIEDDATETIME" DATE
, "NAME" VARCHAR2(50) NOT NULL
, "PRICE" NUMBER(9, 2) NOT NULL
, CONSTRAINT "SHIPPINGMETHOD_UK1" UNIQUE ("NAME")
)
TABLESPACE ${tableTablespace}
;

CREATE SEQUENCE ${schemaName}.SHIPPINGMETHOD_SEQ START WITH 1 INCREMENT BY 1 NOMAXVALUE;

COMMENT ON TABLE ${schemaName}.SHIPPINGMETHOD IS 'Shipping Method';
COMMENT ON COLUMN ${schemaName}.SHIPPINGMETHOD."ID" IS 'Surrogate primary key - generated from SHIPPINGMETHOD_SEQ sequence';
COMMENT ON COLUMN ${schemaName}.SHIPPINGMETHOD."CREATEDUSERID" IS 'Who created the record';
COMMENT ON COLUMN ${schemaName}.SHIPPINGMETHOD."CREATEDDATETIME" IS 'When (date and time) the record was created';
COMMENT ON COLUMN ${schemaName}.SHIPPINGMETHOD."MODIFIEDUSERID" IS 'Who last modified the record';
COMMENT ON COLUMN ${schemaName}.SHIPPINGMETHOD."MODIFIEDDATETIME" IS 'When (date and time) the record was last modified';
COMMENT ON COLUMN ${schemaName}.SHIPPINGMETHOD."NAME" IS 'Shipping delivery mode';
COMMENT ON COLUMN ${schemaName}.SHIPPINGMETHOD."PRICE" IS 'Shipping Price';


