--liquibase formatted sql

--changeset Novacroft:11.0.80
CREATE TABLE ${schemaName}."ZONEIDDESCRIPTION"
("ID" NUMBER(38) NOT NULL CONSTRAINT "ZONEIDDESCRIPTION_PK" PRIMARY KEY
, "CREATEDUSERID" VARCHAR2(64) NOT NULL
, "CREATEDDATETIME" DATE NOT NULL
, "MODIFIEDUSERID" VARCHAR2(64)
, "MODIFIEDDATETIME" DATE
, "DESCRIPTION" VARCHAR2(50) NOT NULL
)
TABLESPACE ${tableTablespace}
;

COMMENT ON TABLE ${schemaName}.ZONEIDDESCRIPTION IS 'Zone id Description';
COMMENT ON COLUMN ${schemaName}.ZONEIDDESCRIPTION."ID" IS 'Surrogate primary key';
COMMENT ON COLUMN ${schemaName}.ZONEIDDESCRIPTION."CREATEDUSERID" IS 'Who created the record';
COMMENT ON COLUMN ${schemaName}.ZONEIDDESCRIPTION."CREATEDDATETIME" IS 'When (date and time) the record was created';
COMMENT ON COLUMN ${schemaName}.ZONEIDDESCRIPTION."MODIFIEDUSERID" IS 'Who last modified the record';
COMMENT ON COLUMN ${schemaName}.ZONEIDDESCRIPTION."MODIFIEDDATETIME" IS 'When (date and time) the record was last modified';
COMMENT ON COLUMN ${schemaName}.ZONEIDDESCRIPTION."DESCRIPTION" IS 'Zone id description';
