--liquibase formatted sql

--changeset Novacroft:11.0.83
INSERT INTO ${schemaName}.ALTERNATIVEZONEMAPPING
( "ID", "CREATEDUSERID", "CREATEDDATETIME", "MODIFIEDUSERID", "MODIFIEDDATETIME", "STARTZONE", "ENDZONE", "ALTERNATIVESTARTZONE", "ALTERNATIVEENDZONE")
VALUES
(${schemaName}.ALTERNATIVEZONEMAPPING_SEQ.nextval, 'Installer', SYSDATE, NULL, NULL, '2', '8', '2', '9');

INSERT INTO ${schemaName}.ALTERNATIVEZONEMAPPING
( "ID", "CREATEDUSERID", "CREATEDDATETIME", "MODIFIEDUSERID", "MODIFIEDDATETIME", "STARTZONE", "ENDZONE", "ALTERNATIVESTARTZONE", "ALTERNATIVEENDZONE")
VALUES
(${schemaName}.ALTERNATIVEZONEMAPPING_SEQ.nextval, 'Installer', SYSDATE, NULL, NULL, '3', '7', '2', '7');

INSERT INTO ${schemaName}.ALTERNATIVEZONEMAPPING
( "ID", "CREATEDUSERID", "CREATEDDATETIME", "MODIFIEDUSERID", "MODIFIEDDATETIME", "STARTZONE", "ENDZONE", "ALTERNATIVESTARTZONE", "ALTERNATIVEENDZONE")
VALUES
(${schemaName}.ALTERNATIVEZONEMAPPING_SEQ.nextval, 'Installer', SYSDATE, NULL, NULL, '3', '8', '2', '9');

INSERT INTO ${schemaName}.ALTERNATIVEZONEMAPPING
( "ID", "CREATEDUSERID", "CREATEDDATETIME", "MODIFIEDUSERID", "MODIFIEDDATETIME", "STARTZONE", "ENDZONE", "ALTERNATIVESTARTZONE", "ALTERNATIVEENDZONE")
VALUES
(${schemaName}.ALTERNATIVEZONEMAPPING_SEQ.nextval, 'Installer', SYSDATE, NULL, NULL, '3', '9', '2', '9');

INSERT INTO ${schemaName}.ALTERNATIVEZONEMAPPING
( "ID", "CREATEDUSERID", "CREATEDDATETIME", "MODIFIEDUSERID", "MODIFIEDDATETIME", "STARTZONE", "ENDZONE", "ALTERNATIVESTARTZONE", "ALTERNATIVEENDZONE")
VALUES
(${schemaName}.ALTERNATIVEZONEMAPPING_SEQ.nextval, 'Installer', SYSDATE, NULL, NULL, '3', '10', '2', '10');

INSERT INTO ${schemaName}.ALTERNATIVEZONEMAPPING
( "ID", "CREATEDUSERID", "CREATEDDATETIME", "MODIFIEDUSERID", "MODIFIEDDATETIME", "STARTZONE", "ENDZONE", "ALTERNATIVESTARTZONE", "ALTERNATIVEENDZONE")
VALUES
(${schemaName}.ALTERNATIVEZONEMAPPING_SEQ.nextval, 'Installer', SYSDATE, NULL, NULL, '3', '11', '2', '11');

INSERT INTO ${schemaName}.ALTERNATIVEZONEMAPPING
( "ID", "CREATEDUSERID", "CREATEDDATETIME", "MODIFIEDUSERID", "MODIFIEDDATETIME", "STARTZONE", "ENDZONE", "ALTERNATIVESTARTZONE", "ALTERNATIVEENDZONE")
VALUES
(${schemaName}.ALTERNATIVEZONEMAPPING_SEQ.nextval, 'Installer', SYSDATE, NULL, NULL, '3', '12', '2', '12');

INSERT INTO ${schemaName}.ALTERNATIVEZONEMAPPING
( "ID", "CREATEDUSERID", "CREATEDDATETIME", "MODIFIEDUSERID", "MODIFIEDDATETIME", "STARTZONE", "ENDZONE", "ALTERNATIVESTARTZONE", "ALTERNATIVEENDZONE")
VALUES
(${schemaName}.ALTERNATIVEZONEMAPPING_SEQ.nextval, 'Installer', SYSDATE, NULL, NULL, '4', '8', '4', '9');

INSERT INTO ${schemaName}.ALTERNATIVEZONEMAPPING
( "ID", "CREATEDUSERID", "CREATEDDATETIME", "MODIFIEDUSERID", "MODIFIEDDATETIME", "STARTZONE", "ENDZONE", "ALTERNATIVESTARTZONE", "ALTERNATIVEENDZONE")
VALUES
(${schemaName}.ALTERNATIVEZONEMAPPING_SEQ.nextval, 'Installer', SYSDATE, NULL, NULL, '4', '11', '2', '11');

INSERT INTO ${schemaName}.ALTERNATIVEZONEMAPPING
( "ID", "CREATEDUSERID", "CREATEDDATETIME", "MODIFIEDUSERID", "MODIFIEDDATETIME", "STARTZONE", "ENDZONE", "ALTERNATIVESTARTZONE", "ALTERNATIVEENDZONE")
VALUES
(${schemaName}.ALTERNATIVEZONEMAPPING_SEQ.nextval, 'Installer', SYSDATE, NULL, NULL, '4', '12', '2', '12');

INSERT INTO ${schemaName}.ALTERNATIVEZONEMAPPING
( "ID", "CREATEDUSERID", "CREATEDDATETIME", "MODIFIEDUSERID", "MODIFIEDDATETIME", "STARTZONE", "ENDZONE", "ALTERNATIVESTARTZONE", "ALTERNATIVEENDZONE")
VALUES
(${schemaName}.ALTERNATIVEZONEMAPPING_SEQ.nextval, 'Installer', SYSDATE, NULL, NULL, '5', '7', '4', '7');

INSERT INTO ${schemaName}.ALTERNATIVEZONEMAPPING
( "ID", "CREATEDUSERID", "CREATEDDATETIME", "MODIFIEDUSERID", "MODIFIEDDATETIME", "STARTZONE", "ENDZONE", "ALTERNATIVESTARTZONE", "ALTERNATIVEENDZONE")
VALUES
(${schemaName}.ALTERNATIVEZONEMAPPING_SEQ.nextval, 'Installer', SYSDATE, NULL, NULL, '5', '8', '4', '9');

INSERT INTO ${schemaName}.ALTERNATIVEZONEMAPPING
( "ID", "CREATEDUSERID", "CREATEDDATETIME", "MODIFIEDUSERID", "MODIFIEDDATETIME", "STARTZONE", "ENDZONE", "ALTERNATIVESTARTZONE", "ALTERNATIVEENDZONE")
VALUES
(${schemaName}.ALTERNATIVEZONEMAPPING_SEQ.nextval, 'Installer', SYSDATE, NULL, NULL, '5', '9', '4', '9');

INSERT INTO ${schemaName}.ALTERNATIVEZONEMAPPING
( "ID", "CREATEDUSERID", "CREATEDDATETIME", "MODIFIEDUSERID", "MODIFIEDDATETIME", "STARTZONE", "ENDZONE", "ALTERNATIVESTARTZONE", "ALTERNATIVEENDZONE")
VALUES
(${schemaName}.ALTERNATIVEZONEMAPPING_SEQ.nextval, 'Installer', SYSDATE, NULL, NULL, '5', '10', '4', '10');

INSERT INTO ${schemaName}.ALTERNATIVEZONEMAPPING
( "ID", "CREATEDUSERID", "CREATEDDATETIME", "MODIFIEDUSERID", "MODIFIEDDATETIME", "STARTZONE", "ENDZONE", "ALTERNATIVESTARTZONE", "ALTERNATIVEENDZONE")
VALUES
(${schemaName}.ALTERNATIVEZONEMAPPING_SEQ.nextval, 'Installer', SYSDATE, NULL, NULL, '5', '11', '2', '11');

INSERT INTO ${schemaName}.ALTERNATIVEZONEMAPPING
( "ID", "CREATEDUSERID", "CREATEDDATETIME", "MODIFIEDUSERID", "MODIFIEDDATETIME", "STARTZONE", "ENDZONE", "ALTERNATIVESTARTZONE", "ALTERNATIVEENDZONE")
VALUES
(${schemaName}.ALTERNATIVEZONEMAPPING_SEQ.nextval, 'Installer', SYSDATE, NULL, NULL, '5', '12', '2', '12');

INSERT INTO ${schemaName}.ALTERNATIVEZONEMAPPING
( "ID", "CREATEDUSERID", "CREATEDDATETIME", "MODIFIEDUSERID", "MODIFIEDDATETIME", "STARTZONE", "ENDZONE", "ALTERNATIVESTARTZONE", "ALTERNATIVEENDZONE")
VALUES
(${schemaName}.ALTERNATIVEZONEMAPPING_SEQ.nextval, 'Installer', SYSDATE, NULL, NULL, '6', '7', '4', '7');

INSERT INTO ${schemaName}.ALTERNATIVEZONEMAPPING
( "ID", "CREATEDUSERID", "CREATEDDATETIME", "MODIFIEDUSERID", "MODIFIEDDATETIME", "STARTZONE", "ENDZONE", "ALTERNATIVESTARTZONE", "ALTERNATIVEENDZONE")
VALUES
(${schemaName}.ALTERNATIVEZONEMAPPING_SEQ.nextval, 'Installer', SYSDATE, NULL, NULL, '6', '8', '4', '9');

INSERT INTO ${schemaName}.ALTERNATIVEZONEMAPPING
( "ID", "CREATEDUSERID", "CREATEDDATETIME", "MODIFIEDUSERID", "MODIFIEDDATETIME", "STARTZONE", "ENDZONE", "ALTERNATIVESTARTZONE", "ALTERNATIVEENDZONE")
VALUES
(${schemaName}.ALTERNATIVEZONEMAPPING_SEQ.nextval, 'Installer', SYSDATE, NULL, NULL, '6', '9', '4', '9');

INSERT INTO ${schemaName}.ALTERNATIVEZONEMAPPING
( "ID", "CREATEDUSERID", "CREATEDDATETIME", "MODIFIEDUSERID", "MODIFIEDDATETIME", "STARTZONE", "ENDZONE", "ALTERNATIVESTARTZONE", "ALTERNATIVEENDZONE")
VALUES
(${schemaName}.ALTERNATIVEZONEMAPPING_SEQ.nextval, 'Installer', SYSDATE, NULL, NULL, '6', '10', '4', '10');

INSERT INTO ${schemaName}.ALTERNATIVEZONEMAPPING
( "ID", "CREATEDUSERID", "CREATEDDATETIME", "MODIFIEDUSERID", "MODIFIEDDATETIME", "STARTZONE", "ENDZONE", "ALTERNATIVESTARTZONE", "ALTERNATIVEENDZONE")
VALUES
(${schemaName}.ALTERNATIVEZONEMAPPING_SEQ.nextval, 'Installer', SYSDATE, NULL, NULL, '6', '11', '2', '11');

INSERT INTO ${schemaName}.ALTERNATIVEZONEMAPPING
( "ID", "CREATEDUSERID", "CREATEDDATETIME", "MODIFIEDUSERID", "MODIFIEDDATETIME", "STARTZONE", "ENDZONE", "ALTERNATIVESTARTZONE", "ALTERNATIVEENDZONE")
VALUES
(${schemaName}.ALTERNATIVEZONEMAPPING_SEQ.nextval, 'Installer', SYSDATE, NULL, NULL, '6', '12', '2', '12');

INSERT INTO ${schemaName}.ALTERNATIVEZONEMAPPING
( "ID", "CREATEDUSERID", "CREATEDDATETIME", "MODIFIEDUSERID", "MODIFIEDDATETIME", "STARTZONE", "ENDZONE", "ALTERNATIVESTARTZONE", "ALTERNATIVEENDZONE")
VALUES
(${schemaName}.ALTERNATIVEZONEMAPPING_SEQ.nextval, 'Installer', SYSDATE, NULL, NULL, '7', '8', '4', '9');

INSERT INTO ${schemaName}.ALTERNATIVEZONEMAPPING
( "ID", "CREATEDUSERID", "CREATEDDATETIME", "MODIFIEDUSERID", "MODIFIEDDATETIME", "STARTZONE", "ENDZONE", "ALTERNATIVESTARTZONE", "ALTERNATIVEENDZONE")
VALUES
(${schemaName}.ALTERNATIVEZONEMAPPING_SEQ.nextval, 'Installer', SYSDATE, NULL, NULL, '7', '9', '4', '9');

INSERT INTO ${schemaName}.ALTERNATIVEZONEMAPPING
( "ID", "CREATEDUSERID", "CREATEDDATETIME", "MODIFIEDUSERID", "MODIFIEDDATETIME", "STARTZONE", "ENDZONE", "ALTERNATIVESTARTZONE", "ALTERNATIVEENDZONE")
VALUES
(${schemaName}.ALTERNATIVEZONEMAPPING_SEQ.nextval, 'Installer', SYSDATE, NULL, NULL, '7', '10', '4', '10');

INSERT INTO ${schemaName}.ALTERNATIVEZONEMAPPING
( "ID", "CREATEDUSERID", "CREATEDDATETIME", "MODIFIEDUSERID", "MODIFIEDDATETIME", "STARTZONE", "ENDZONE", "ALTERNATIVESTARTZONE", "ALTERNATIVEENDZONE")
VALUES
(${schemaName}.ALTERNATIVEZONEMAPPING_SEQ.nextval, 'Installer', SYSDATE, NULL, NULL, '7', '11', '2', '11');

INSERT INTO ${schemaName}.ALTERNATIVEZONEMAPPING
( "ID", "CREATEDUSERID", "CREATEDDATETIME", "MODIFIEDUSERID", "MODIFIEDDATETIME", "STARTZONE", "ENDZONE", "ALTERNATIVESTARTZONE", "ALTERNATIVEENDZONE")
VALUES
(${schemaName}.ALTERNATIVEZONEMAPPING_SEQ.nextval, 'Installer', SYSDATE, NULL, NULL, '7', '12', '2', '12');

INSERT INTO ${schemaName}.ALTERNATIVEZONEMAPPING
( "ID", "CREATEDUSERID", "CREATEDDATETIME", "MODIFIEDUSERID", "MODIFIEDDATETIME", "STARTZONE", "ENDZONE", "ALTERNATIVESTARTZONE", "ALTERNATIVEENDZONE")
VALUES
(${schemaName}.ALTERNATIVEZONEMAPPING_SEQ.nextval, 'Installer', SYSDATE, NULL, NULL, '8', '9', '4', '9');

INSERT INTO ${schemaName}.ALTERNATIVEZONEMAPPING
( "ID", "CREATEDUSERID", "CREATEDDATETIME", "MODIFIEDUSERID", "MODIFIEDDATETIME", "STARTZONE", "ENDZONE", "ALTERNATIVESTARTZONE", "ALTERNATIVEENDZONE")
VALUES
(${schemaName}.ALTERNATIVEZONEMAPPING_SEQ.nextval, 'Installer', SYSDATE, NULL, NULL, '8', '10', '4', '10');

INSERT INTO ${schemaName}.ALTERNATIVEZONEMAPPING
( "ID", "CREATEDUSERID", "CREATEDDATETIME", "MODIFIEDUSERID", "MODIFIEDDATETIME", "STARTZONE", "ENDZONE", "ALTERNATIVESTARTZONE", "ALTERNATIVEENDZONE")
VALUES
(${schemaName}.ALTERNATIVEZONEMAPPING_SEQ.nextval, 'Installer', SYSDATE, NULL, NULL, '8', '11', '2', '11');

INSERT INTO ${schemaName}.ALTERNATIVEZONEMAPPING
( "ID", "CREATEDUSERID", "CREATEDDATETIME", "MODIFIEDUSERID", "MODIFIEDDATETIME", "STARTZONE", "ENDZONE", "ALTERNATIVESTARTZONE", "ALTERNATIVEENDZONE")
VALUES
(${schemaName}.ALTERNATIVEZONEMAPPING_SEQ.nextval, 'Installer', SYSDATE, NULL, NULL, '8', '12', '2', '12');

INSERT INTO ${schemaName}.ALTERNATIVEZONEMAPPING
( "ID", "CREATEDUSERID", "CREATEDDATETIME", "MODIFIEDUSERID", "MODIFIEDDATETIME", "STARTZONE", "ENDZONE", "ALTERNATIVESTARTZONE", "ALTERNATIVEENDZONE")
VALUES
(${schemaName}.ALTERNATIVEZONEMAPPING_SEQ.nextval, 'Installer', SYSDATE, NULL, NULL, '9', '10', '4', '10');

INSERT INTO ${schemaName}.ALTERNATIVEZONEMAPPING
( "ID", "CREATEDUSERID", "CREATEDDATETIME", "MODIFIEDUSERID", "MODIFIEDDATETIME", "STARTZONE", "ENDZONE", "ALTERNATIVESTARTZONE", "ALTERNATIVEENDZONE")
VALUES
(${schemaName}.ALTERNATIVEZONEMAPPING_SEQ.nextval, 'Installer', SYSDATE, NULL, NULL, '9', '11', '2', '11');

INSERT INTO ${schemaName}.ALTERNATIVEZONEMAPPING
( "ID", "CREATEDUSERID", "CREATEDDATETIME", "MODIFIEDUSERID", "MODIFIEDDATETIME", "STARTZONE", "ENDZONE", "ALTERNATIVESTARTZONE", "ALTERNATIVEENDZONE")
VALUES
(${schemaName}.ALTERNATIVEZONEMAPPING_SEQ.nextval, 'Installer', SYSDATE, NULL, NULL, '9', '12', '2', '12');

INSERT INTO ${schemaName}.ALTERNATIVEZONEMAPPING
( "ID", "CREATEDUSERID", "CREATEDDATETIME", "MODIFIEDUSERID", "MODIFIEDDATETIME", "STARTZONE", "ENDZONE", "ALTERNATIVESTARTZONE", "ALTERNATIVEENDZONE")
VALUES
(${schemaName}.ALTERNATIVEZONEMAPPING_SEQ.nextval, 'Installer', SYSDATE, NULL, NULL, '10', '11', '2', '11');

INSERT INTO ${schemaName}.ALTERNATIVEZONEMAPPING
( "ID", "CREATEDUSERID", "CREATEDDATETIME", "MODIFIEDUSERID", "MODIFIEDDATETIME", "STARTZONE", "ENDZONE", "ALTERNATIVESTARTZONE", "ALTERNATIVEENDZONE")
VALUES
(${schemaName}.ALTERNATIVEZONEMAPPING_SEQ.nextval, 'Installer', SYSDATE, NULL, NULL, '10', '12', '2', '12');

INSERT INTO ${schemaName}.ALTERNATIVEZONEMAPPING
( "ID", "CREATEDUSERID", "CREATEDDATETIME", "MODIFIEDUSERID", "MODIFIEDDATETIME", "STARTZONE", "ENDZONE", "ALTERNATIVESTARTZONE", "ALTERNATIVEENDZONE")
VALUES
(${schemaName}.ALTERNATIVEZONEMAPPING_SEQ.nextval, 'Installer', SYSDATE, NULL, NULL, '11', '12', '2', '12');