--liquibase formatted sql

--changeset Novacroft:11.0.180

CREATE SEQUENCE ${schemaName}."REFUNDSCENARIOHOTLISTTYPE_SEQ";

CREATE TABLE ${schemaName}."REFUNDSCENARIOHOTLISTTYPE"
("ID" NUMBER(38) NOT NULL CONSTRAINT "REFUNDSCENARIOHOTLISTTYPE_PK" PRIMARY KEY
, "CREATEDUSERID" VARCHAR2(64) NOT NULL
, "CREATEDDATETIME" DATE NOT NULL
, "MODIFIEDUSERID" VARCHAR2(64)
, "MODIFIEDDATETIME" DATE
, "REFUNDSCENARIO" VARCHAR2(200) CONSTRAINT REFUNDSCENARIOHOTLISTTYPE_UK1 UNIQUE
, "HOTLISTREASON_ID" NUMBER(38)
, CONSTRAINT FK_1 FOREIGN KEY ("HOTLISTREASON_ID") REFERENCES ${schemaName}."HOTLISTREASON"("ID")

)
TABLESPACE ${tableTablespace}
;

COMMENT ON TABLE ${schemaName}."REFUNDSCENARIOHOTLISTTYPE" IS 'Relates Refund Scenarios to the hotlist reasons';
COMMENT ON COLUMN ${schemaName}."REFUNDSCENARIOHOTLISTTYPE"."ID" IS 'Surrogate primary key';
COMMENT ON COLUMN ${schemaName}."REFUNDSCENARIOHOTLISTTYPE"."CREATEDUSERID" IS 'Who created the record';
COMMENT ON COLUMN ${schemaName}."REFUNDSCENARIOHOTLISTTYPE"."CREATEDDATETIME" IS 'When (date and time) the record was created';
COMMENT ON COLUMN ${schemaName}."REFUNDSCENARIOHOTLISTTYPE"."MODIFIEDUSERID" IS 'Who last modified the record';
COMMENT ON COLUMN ${schemaName}."REFUNDSCENARIOHOTLISTTYPE"."MODIFIEDDATETIME" IS 'When (date and time) the record was last modified';
COMMENT ON COLUMN ${schemaName}."REFUNDSCENARIOHOTLISTTYPE"."REFUNDSCENARIO" IS 'The refund scenario which refers to enum in java code ';
COMMENT ON COLUMN ${schemaName}."REFUNDSCENARIOHOTLISTTYPE"."HOTLISTREASON_ID" IS 'Foreign key of the hot list reason is';


INSERT INTO ${schemaName}.REFUNDSCENARIOHOTLISTTYPE ( "ID", "CREATEDUSERID", "CREATEDDATETIME", "MODIFIEDUSERID", "MODIFIEDDATETIME", "REFUNDSCENARIO", "HOTLISTREASON_ID")
VALUES
(${schemaName}.REFUNDSCENARIOHOTLISTTYPE_SEQ.nextval, 'Installer', SYSDATE, NULL, NULL, 'FailedCardRefund', 18);
INSERT INTO ${schemaName}.REFUNDSCENARIOHOTLISTTYPE ( "ID", "CREATEDUSERID", "CREATEDDATETIME", "MODIFIEDUSERID", "MODIFIEDDATETIME", "REFUNDSCENARIO", "HOTLISTREASON_ID")
VALUES
(${schemaName}.REFUNDSCENARIOHOTLISTTYPE_SEQ.nextval, 'Installer', SYSDATE, NULL, NULL, 'LostRefund', 1);
INSERT INTO ${schemaName}.REFUNDSCENARIOHOTLISTTYPE ( "ID", "CREATEDUSERID", "CREATEDDATETIME", "MODIFIEDUSERID", "MODIFIEDDATETIME", "REFUNDSCENARIO", "HOTLISTREASON_ID")
VALUES
(${schemaName}.REFUNDSCENARIOHOTLISTTYPE_SEQ.nextval, 'Installer', SYSDATE, NULL, NULL, 'StolenRefund', 2);
INSERT INTO ${schemaName}.REFUNDSCENARIOHOTLISTTYPE ( "ID", "CREATEDUSERID", "CREATEDDATETIME", "MODIFIEDUSERID", "MODIFIEDDATETIME", "REFUNDSCENARIO", "HOTLISTREASON_ID")
VALUES
(${schemaName}.REFUNDSCENARIOHOTLISTTYPE_SEQ.nextval, 'Installer', SYSDATE, NULL, NULL, 'CancelAndSurrender', 15);
INSERT INTO ${schemaName}.REFUNDSCENARIOHOTLISTTYPE ( "ID", "CREATEDUSERID", "CREATEDDATETIME", "MODIFIEDUSERID", "MODIFIEDDATETIME", "REFUNDSCENARIO", "HOTLISTREASON_ID")
VALUES
(${schemaName}.REFUNDSCENARIOHOTLISTTYPE_SEQ.nextval, 'Installer', SYSDATE, NULL, NULL, 'Other', 13);
INSERT INTO ${schemaName}.REFUNDSCENARIOHOTLISTTYPE ( "ID", "CREATEDUSERID", "CREATEDDATETIME", "MODIFIEDUSERID", "MODIFIEDDATETIME", "REFUNDSCENARIO", "HOTLISTREASON_ID")
VALUES
(${schemaName}.REFUNDSCENARIOHOTLISTTYPE_SEQ.nextval, 'Installer', SYSDATE, NULL, NULL, 'Destroyed', 20);

	 
  
