--liquibase formatted sql

--changeset Novacroft:11.0.85
INSERT INTO ${schemaName}.PAYASYOUGO
( "ID", "CREATEDUSERID", "CREATEDDATETIME", "MODIFIEDUSERID", "MODIFIEDDATETIME", "PAYASYOUGONAME", "TICKETPRICE")
VALUES
(${schemaName}.PAYASYOUGO_SEQ.nextval, 'Installer', SYSDATE, NULL, NULL, 'Pay as you go credit', '0');

INSERT INTO ${schemaName}.PAYASYOUGO
( "ID", "CREATEDUSERID", "CREATEDDATETIME", "MODIFIEDUSERID", "MODIFIEDDATETIME", "PAYASYOUGONAME", "TICKETPRICE")
VALUES
(${schemaName}.PAYASYOUGO_SEQ.nextval, 'Installer', SYSDATE, NULL, NULL, 'Pay as you go credit', '500');

INSERT INTO ${schemaName}.PAYASYOUGO
( "ID", "CREATEDUSERID", "CREATEDDATETIME", "MODIFIEDUSERID", "MODIFIEDDATETIME", "PAYASYOUGONAME", "TICKETPRICE")
VALUES
(${schemaName}.PAYASYOUGO_SEQ.nextval, 'Installer', SYSDATE, NULL, NULL, 'Pay as you go credit', '1000');

INSERT INTO ${schemaName}.PAYASYOUGO
( "ID", "CREATEDUSERID", "CREATEDDATETIME", "MODIFIEDUSERID", "MODIFIEDDATETIME", "PAYASYOUGONAME", "TICKETPRICE")
VALUES
(${schemaName}.PAYASYOUGO_SEQ.nextval, 'Installer', SYSDATE, NULL, NULL, 'Pay as you go credit', '1500');

INSERT INTO ${schemaName}.PAYASYOUGO
( "ID", "CREATEDUSERID", "CREATEDDATETIME", "MODIFIEDUSERID", "MODIFIEDDATETIME", "PAYASYOUGONAME", "TICKETPRICE")
VALUES
(${schemaName}.PAYASYOUGO_SEQ.nextval, 'Installer', SYSDATE, NULL, NULL, 'Pay as you go credit', '2000');

INSERT INTO ${schemaName}.PAYASYOUGO
( "ID", "CREATEDUSERID", "CREATEDDATETIME", "MODIFIEDUSERID", "MODIFIEDDATETIME", "PAYASYOUGONAME", "TICKETPRICE")
VALUES
(${schemaName}.PAYASYOUGO_SEQ.nextval, 'Installer', SYSDATE, NULL, NULL, 'Pay as you go credit', '2500');

INSERT INTO ${schemaName}.PAYASYOUGO
( "ID", "CREATEDUSERID", "CREATEDDATETIME", "MODIFIEDUSERID", "MODIFIEDDATETIME", "PAYASYOUGONAME", "TICKETPRICE")
VALUES
(${schemaName}.PAYASYOUGO_SEQ.nextval, 'Installer', SYSDATE, NULL, NULL, 'Pay as you go credit', '3000');

INSERT INTO ${schemaName}.PAYASYOUGO
( "ID", "CREATEDUSERID", "CREATEDDATETIME", "MODIFIEDUSERID", "MODIFIEDDATETIME", "PAYASYOUGONAME", "TICKETPRICE")
VALUES
(${schemaName}.PAYASYOUGO_SEQ.nextval, 'Installer', SYSDATE, NULL, NULL, 'Pay as you go credit', '3500');

INSERT INTO ${schemaName}.PAYASYOUGO
( "ID", "CREATEDUSERID", "CREATEDDATETIME", "MODIFIEDUSERID", "MODIFIEDDATETIME", "PAYASYOUGONAME", "TICKETPRICE")
VALUES
(${schemaName}.PAYASYOUGO_SEQ.nextval, 'Installer', SYSDATE, NULL, NULL, 'Pay as you go credit', '4000');

INSERT INTO ${schemaName}.PAYASYOUGO
( "ID", "CREATEDUSERID", "CREATEDDATETIME", "MODIFIEDUSERID", "MODIFIEDDATETIME", "PAYASYOUGONAME", "TICKETPRICE")
VALUES
(${schemaName}.PAYASYOUGO_SEQ.nextval, 'Installer', SYSDATE, NULL, NULL, 'Pay as you go credit', '4500');

INSERT INTO ${schemaName}.PAYASYOUGO
( "ID", "CREATEDUSERID", "CREATEDDATETIME", "MODIFIEDUSERID", "MODIFIEDDATETIME", "PAYASYOUGONAME", "TICKETPRICE")
VALUES
(${schemaName}.PAYASYOUGO_SEQ.nextval, 'Installer', SYSDATE, NULL, NULL, 'Pay as you go credit', '5000');