--liquibase formatted sql

--changeset Novacroft:11.0.116
INSERT INTO ${schemaName}.AUTOTOPUP
( "ID", "CREATEDUSERID", "CREATEDDATETIME", "MODIFIEDUSERID", "MODIFIEDDATETIME", "AUTOTOPUPAMOUNT")
VALUES
(${schemaName}.PAYASYOUGO_SEQ.nextval, 'Installer', SYSDATE, NULL, NULL, '0');

INSERT INTO ${schemaName}.AUTOTOPUP
( "ID", "CREATEDUSERID", "CREATEDDATETIME", "MODIFIEDUSERID", "MODIFIEDDATETIME", "AUTOTOPUPAMOUNT")
VALUES
(${schemaName}.PAYASYOUGO_SEQ.nextval, 'Installer', SYSDATE, NULL, NULL, '2000');

INSERT INTO ${schemaName}.AUTOTOPUP
( "ID", "CREATEDUSERID", "CREATEDDATETIME", "MODIFIEDUSERID", "MODIFIEDDATETIME", "AUTOTOPUPAMOUNT")
VALUES
(${schemaName}.PAYASYOUGO_SEQ.nextval, 'Installer', SYSDATE, NULL, NULL, '4000');