--liquibase formatted sql

--changeset Novacroft:11.0.89
CREATE TABLE ${schemaName}.AGENTWEBACCOUNTACCESS
(
"ID" NUMBER
, "AGENTID" VARCHAR2(10 BYTE)
, "WEBACCOUNTID" NUMBER
, "CUSTOMERID" NUMBER
, "TOKEN" VARCHAR2(20 BYTE)
, "CREATEDUSERID" VARCHAR2(64) NOT NULL
, "CREATEDDATETIME" DATE NOT NULL
, "MODIFIEDUSERID" VARCHAR2(64)
, "MODIFIEDDATETIME" DATE
) TABLESPACE ${tableTablespace};

COMMENT ON COLUMN ${schemaName}."AGENTWEBACCOUNTACCESS"."ID" IS 'primary key';
COMMENT ON COLUMN ${schemaName}."AGENTWEBACCOUNTACCESS"."AGENTID" IS 'USERID of the agent logged in Innovator';
COMMENT ON COLUMN ${schemaName}."AGENTWEBACCOUNTACCESS"."WEBACCOUNTID" IS 'Webaccount that the agent wants to log in';
COMMENT ON COLUMN ${schemaName}."AGENTWEBACCOUNTACCESS"."CUSTOMERID" IS 'Customer account that the agent wants to log into';
COMMENT ON COLUMN ${schemaName}."AGENTWEBACCOUNTACCESS"."TOKEN" IS 'One time token to allow access for the agent to the webaccount';
COMMENT ON COLUMN ${schemaName}."AGENTWEBACCOUNTACCESS"."CREATEDUSERID" IS 'Who created the record';
COMMENT ON COLUMN ${schemaName}."AGENTWEBACCOUNTACCESS"."CREATEDDATETIME" IS 'When (date and time) the record was created';
COMMENT ON COLUMN ${schemaName}."AGENTWEBACCOUNTACCESS"."MODIFIEDUSERID" IS 'Who last modified the record';
COMMENT ON COLUMN ${schemaName}."AGENTWEBACCOUNTACCESS"."MODIFIEDDATETIME" IS 'When (date and time) the record was last modified';


CREATE INDEX ${schemaName}."AGENTWEBACCOUNTACCESS1" ON ${schemaName}."AGENTWEBACCOUNTACCESS"
( "ID" )
TABLESPACE ${indexTablespace}
;

CREATE INDEX ${schemaName}."AGENTWEBACCOUNTACCESS2" ON ${schemaName}."AGENTWEBACCOUNTACCESS"
( "AGENTID" )
TABLESPACE ${indexTablespace}
;


CREATE INDEX ${schemaName}."AGENTWEBACCOUNTACCESS3" ON ${schemaName}."AGENTWEBACCOUNTACCESS"
( "WEBACCOUNTID" )
TABLESPACE ${indexTablespace}
;

CREATE INDEX ${schemaName}."AGENTWEBACCOUNTACCESS4" ON ${schemaName}."AGENTWEBACCOUNTACCESS"
( "CUSTOMERID" )
TABLESPACE ${indexTablespace}
;

CREATE SEQUENCE ${schemaName}.AGENTWEBACCOUNTACCESS_SEQ INCREMENT BY 1 NOMAXVALUE;


CREATE TABLE ${schemaName}.AGENTWEBACCOUNTACCESS_AUD
(
"REV" NUMBER NOT NULL
, "REVTYPE" NUMBER NOT NULL
,"ID" NUMBER
, "AGENTID" VARCHAR2(10 BYTE)
, "WEBACCOUNTID" NUMBER
, "CUSTOMERID" NUMBER
, "TOKEN" VARCHAR2(20 BYTE)
, "CREATEDUSERID" VARCHAR2(64)
, "CREATEDDATETIME" DATE
, "MODIFIEDUSERID" VARCHAR2(64)
, "MODIFIEDDATETIME" DATE
) TABLESPACE ${tableTablespace};

INSERT INTO ${schemaName}.content
( "ID", "CREATEDUSERID", "CREATEDDATETIME", "MODIFIEDUSERID", "MODIFIEDDATETIME", "CODE", "LOCALE", "CONTENT")
VALUES
(${schemaName}.content_seq.nextval, 'Installer', SYSDATE, NULL, NULL, 'openwebaccount.button.label', 'en_GB', 'Login to web account');
