--liquibase formatted sql

--changeset Novacroft:11.0.163
CREATE TABLE ${schemaName}."CLAIMLIMITTHRESHOLD"
("ID" NUMBER(38) NOT NULL CONSTRAINT "CLAIMLIMITTHRESHOLD_PK" PRIMARY KEY
, "CREATEDUSERID" VARCHAR2(64) NOT NULL
, "CREATEDDATETIME" DATE NOT NULL
, "MODIFIEDUSERID" VARCHAR2(64)
, "MODIFIEDDATETIME" DATE
, "DEPARTMENT" VARCHAR2(256) NOT NULL
, "SCENARIO" VARCHAR2(256)
, "REFUND_TYPE" VARCHAR2(256)
, "BASIS" VARCHAR2(256)
, "MINVALUETHRESHOLD" NUMBER
, "MAXVALUETHRESHOLD" NUMBER
, "PERCENTAGETOAPPROVE" NUMBER
, "INSTANCETHRESHOLD" NUMBER
, "RULETYPE" VARCHAR2(256) NOT NULL
)
TABLESPACE ${tableTablespace}
;


CREATE SEQUENCE ${schemaName}."CLAIMLIMITTHRESHOLD_SEQ";

COMMENT ON TABLE ${schemaName}."CLAIMLIMITTHRESHOLD" IS 'Random sample approval rules and random sample size';
COMMENT ON COLUMN ${schemaName}."CLAIMLIMITTHRESHOLD"."ID" IS 'Surrogate primary key - generated from CLAIMLIMITTHRESHOLD_SEQ sequence';
COMMENT ON COLUMN ${schemaName}."CLAIMLIMITTHRESHOLD"."CREATEDUSERID" IS 'Who created the record';
COMMENT ON COLUMN ${schemaName}."CLAIMLIMITTHRESHOLD"."CREATEDDATETIME" IS 'When (date and time) the record was created';
COMMENT ON COLUMN ${schemaName}."CLAIMLIMITTHRESHOLD"."MODIFIEDUSERID" IS 'Who last modified the record';
COMMENT ON COLUMN ${schemaName}."CLAIMLIMITTHRESHOLD"."MODIFIEDDATETIME" IS 'When (date and time) the record was last modified';
COMMENT ON COLUMN ${schemaName}."CLAIMLIMITTHRESHOLD"."DEPARTMENT" IS 'Refund Department';
COMMENT ON COLUMN ${schemaName}."CLAIMLIMITTHRESHOLD"."SCENARIO" IS 'Refund scenario';
COMMENT ON COLUMN ${schemaName}."CLAIMLIMITTHRESHOLD"."REFUND_TYPE" IS 'sub scenario for RCL rules';
COMMENT ON COLUMN ${schemaName}."CLAIMLIMITTHRESHOLD"."BASIS" IS 'Refund basis';
COMMENT ON COLUMN ${schemaName}."CLAIMLIMITTHRESHOLD"."MINVALUETHRESHOLD" IS 'Minimum refund amount for this rule';
COMMENT ON COLUMN ${schemaName}."CLAIMLIMITTHRESHOLD"."MAXVALUETHRESHOLD" IS 'Maximum refund amount for this rule';
COMMENT ON COLUMN ${schemaName}."CLAIMLIMITTHRESHOLD"."PERCENTAGETOAPPROVE" IS 'Quantity as percentage of refunds to send for approval that meet this rule';
COMMENT ON COLUMN ${schemaName}."CLAIMLIMITTHRESHOLD"."INSTANCETHRESHOLD" IS 'Rule violation threshold quantity';
COMMENT ON COLUMN ${schemaName}."CLAIMLIMITTHRESHOLD"."RULETYPE" IS 'Discriminator between different types of business rules';

CREATE TABLE ${schemaName}."RANDOMAPPROVALSAMPLE"
("ID" NUMBER(38) NOT NULL CONSTRAINT "RANDOMAPPROVALSAMPLE_PK" PRIMARY KEY
, "CREATEDUSERID" VARCHAR2(64) NOT NULL
, "CREATEDDATETIME" DATE NOT NULL
, "MODIFIEDUSERID" VARCHAR2(64)
, "MODIFIEDDATETIME" DATE
, "ORGANISATION" VARCHAR2(256) NOT NULL
, "DEPARTMENT" VARCHAR2(256) NOT NULL
, "TEAM" VARCHAR2(256) NOT NULL
, "SCENARIO" VARCHAR2(256)
, "REFUND_TYPE" VARCHAR2(256)
, "BASIS" VARCHAR2(256)
, "MINVALUETHRESHOLD" NUMBER
, "MAXVALUETHRESHOLD" NUMBER
, "PERCENTAGETOAPPROVE" NUMBER
, "INSTANCETHRESHOLD" NUMBER
, "RULETYPE" VARCHAR2(256) NOT NULL
)
TABLESPACE ${tableTablespace}
;


CREATE SEQUENCE ${schemaName}."RANDOMAPPROVALSAMPLE_SEQ";

COMMENT ON TABLE ${schemaName}."RANDOMAPPROVALSAMPLE" IS 'Random sample approval rules and random sample size';
COMMENT ON COLUMN ${schemaName}."RANDOMAPPROVALSAMPLE"."ID" IS 'Surrogate primary key - generated from RANDOMAPPROVALSAMPLE_SEQ sequence';
COMMENT ON COLUMN ${schemaName}."RANDOMAPPROVALSAMPLE"."CREATEDUSERID" IS 'Who created the record';
COMMENT ON COLUMN ${schemaName}."RANDOMAPPROVALSAMPLE"."CREATEDDATETIME" IS 'When (date and time) the record was created';
COMMENT ON COLUMN ${schemaName}."RANDOMAPPROVALSAMPLE"."MODIFIEDUSERID" IS 'Who last modified the record';
COMMENT ON COLUMN ${schemaName}."RANDOMAPPROVALSAMPLE"."MODIFIEDDATETIME" IS 'When (date and time) the record was last modified';
COMMENT ON COLUMN ${schemaName}."RANDOMAPPROVALSAMPLE"."ORGANISATION" IS 'Refund Organisation to which this rule applies';
COMMENT ON COLUMN ${schemaName}."RANDOMAPPROVALSAMPLE"."DEPARTMENT" IS 'Refund Department to which this rule applies';
COMMENT ON COLUMN ${schemaName}."RANDOMAPPROVALSAMPLE"."TEAM" IS 'Refund Team to which this rule applies';
COMMENT ON COLUMN ${schemaName}."RANDOMAPPROVALSAMPLE"."SCENARIO" IS 'Refund scenario';
COMMENT ON COLUMN ${schemaName}."RANDOMAPPROVALSAMPLE"."REFUND_TYPE" IS 'sub scenario for RCL rules';
COMMENT ON COLUMN ${schemaName}."RANDOMAPPROVALSAMPLE"."BASIS" IS 'Refund basis';
COMMENT ON COLUMN ${schemaName}."RANDOMAPPROVALSAMPLE"."MINVALUETHRESHOLD" IS 'Minimum refund amount for this rule';
COMMENT ON COLUMN ${schemaName}."RANDOMAPPROVALSAMPLE"."MAXVALUETHRESHOLD" IS 'Maximum refund amount for this rule';
COMMENT ON COLUMN ${schemaName}."RANDOMAPPROVALSAMPLE"."PERCENTAGETOAPPROVE" IS 'Quantity as percentage of refunds to send for approval that meet this rule';
COMMENT ON COLUMN ${schemaName}."RANDOMAPPROVALSAMPLE"."INSTANCETHRESHOLD" IS 'Rule violation threshold quantity';
COMMENT ON COLUMN ${schemaName}."RANDOMAPPROVALSAMPLE"."RULETYPE" IS 'Discriminator between different types of business rules';


