--liquibase formatted sql

--changeset Novacroft:11.0.81
INSERT INTO ${schemaName}.ZONEIDDESCRIPTION
( "ID", "CREATEDUSERID", "CREATEDDATETIME", "MODIFIEDUSERID", "MODIFIEDDATETIME", "DESCRIPTION")
VALUES
(1, 'Installer', SYSDATE, NULL, NULL, '1');

INSERT INTO ${schemaName}.ZONEIDDESCRIPTION
( "ID", "CREATEDUSERID", "CREATEDDATETIME", "MODIFIEDUSERID", "MODIFIEDDATETIME", "DESCRIPTION")
VALUES
(2, 'Installer', SYSDATE, NULL, NULL, '2');

INSERT INTO ${schemaName}.ZONEIDDESCRIPTION
( "ID", "CREATEDUSERID", "CREATEDDATETIME", "MODIFIEDUSERID", "MODIFIEDDATETIME", "DESCRIPTION")
VALUES
(3, 'Installer', SYSDATE, NULL, NULL, '3');

INSERT INTO ${schemaName}.ZONEIDDESCRIPTION
( "ID", "CREATEDUSERID", "CREATEDDATETIME", "MODIFIEDUSERID", "MODIFIEDDATETIME", "DESCRIPTION")
VALUES
(4, 'Installer', SYSDATE, NULL, NULL, '4');

INSERT INTO ${schemaName}.ZONEIDDESCRIPTION
( "ID", "CREATEDUSERID", "CREATEDDATETIME", "MODIFIEDUSERID", "MODIFIEDDATETIME", "DESCRIPTION")
VALUES
(5, 'Installer', SYSDATE, NULL, NULL, '5');

INSERT INTO ${schemaName}.ZONEIDDESCRIPTION
( "ID", "CREATEDUSERID", "CREATEDDATETIME", "MODIFIEDUSERID", "MODIFIEDDATETIME", "DESCRIPTION")
VALUES
(6, 'Installer', SYSDATE, NULL, NULL, '6');

INSERT INTO ${schemaName}.ZONEIDDESCRIPTION
( "ID", "CREATEDUSERID", "CREATEDDATETIME", "MODIFIEDUSERID", "MODIFIEDDATETIME", "DESCRIPTION")
VALUES
(7, 'Installer', SYSDATE, NULL, NULL, '7');

INSERT INTO ${schemaName}.ZONEIDDESCRIPTION
( "ID", "CREATEDUSERID", "CREATEDDATETIME", "MODIFIEDUSERID", "MODIFIEDDATETIME", "DESCRIPTION")
VALUES
(8, 'Installer', SYSDATE, NULL, NULL, '8');

INSERT INTO ${schemaName}.ZONEIDDESCRIPTION
( "ID", "CREATEDUSERID", "CREATEDDATETIME", "MODIFIEDUSERID", "MODIFIEDDATETIME", "DESCRIPTION")
VALUES
(9, 'Installer', SYSDATE, NULL, NULL, '9');

INSERT INTO ${schemaName}.ZONEIDDESCRIPTION
( "ID", "CREATEDUSERID", "CREATEDDATETIME", "MODIFIEDUSERID", "MODIFIEDDATETIME", "DESCRIPTION")
VALUES
(10, 'Installer', SYSDATE, NULL, NULL, '9 + Watford Junction');

INSERT INTO ${schemaName}.ZONEIDDESCRIPTION
( "ID", "CREATEDUSERID", "CREATEDDATETIME", "MODIFIEDUSERID", "MODIFIEDDATETIME", "DESCRIPTION")
VALUES
(11, 'Installer', SYSDATE, NULL, NULL, '9 + Watford Junction + Broxbourne + Brentwood');

INSERT INTO ${schemaName}.ZONEIDDESCRIPTION
( "ID", "CREATEDUSERID", "CREATEDDATETIME", "MODIFIEDUSERID", "MODIFIEDDATETIME", "DESCRIPTION")
VALUES
(12, 'Installer', SYSDATE, NULL, NULL, '9 + Watford Junction + Broxbourne + Shenfield');