--liquibase formatted sql

--changeset Novacroft:11.0.114
CREATE TABLE ACT_ID_GROUP (
  ID_   NVARCHAR2(64),
  REV_  INTEGER,
  NAME_ NVARCHAR2(255),
  TYPE_ NVARCHAR2(255),
  PRIMARY KEY (ID_)
);

CREATE TABLE ACT_ID_MEMBERSHIP (
  USER_ID_  NVARCHAR2(64),
  GROUP_ID_ NVARCHAR2(64),
  PRIMARY KEY (USER_ID_, GROUP_ID_)
);

CREATE TABLE ACT_ID_USER (
  ID_         NVARCHAR2(64),
  REV_        INTEGER,
  FIRST_      NVARCHAR2(255),
  LAST_       NVARCHAR2(255),
  EMAIL_      NVARCHAR2(255),
  PWD_        NVARCHAR2(255),
  PICTURE_ID_ NVARCHAR2(64),
  PRIMARY KEY (ID_)
);

CREATE TABLE ACT_ID_INFO (
  ID_        NVARCHAR2(64),
  REV_       INTEGER,
  USER_ID_   NVARCHAR2(64),
  TYPE_      NVARCHAR2(64),
  KEY_       NVARCHAR2(255),
  VALUE_     NVARCHAR2(255),
  PASSWORD_  BLOB,
  PARENT_ID_ NVARCHAR2(255),
  PRIMARY KEY (ID_)
);

CREATE INDEX ACT_IDX_MEMB_GROUP ON ACT_ID_MEMBERSHIP (GROUP_ID_);
ALTER TABLE ACT_ID_MEMBERSHIP
ADD CONSTRAINT ACT_FK_MEMB_GROUP
FOREIGN KEY (GROUP_ID_)
REFERENCES ACT_ID_GROUP (ID_);

CREATE INDEX ACT_IDX_MEMB_USER ON ACT_ID_MEMBERSHIP (USER_ID_);
ALTER TABLE ACT_ID_MEMBERSHIP
ADD CONSTRAINT ACT_FK_MEMB_USER
FOREIGN KEY (USER_ID_)
REFERENCES ACT_ID_USER (ID_);
