--liquibase formatted sql

--changeset Novacroft:11.0.75
CREATE TABLE ${schemaName}.ITEM
( "ID" NUMBER(38) NOT NULL CONSTRAINT ITEM_PK PRIMARY KEY
, "CREATEDUSERID" VARCHAR2(64) NOT NULL
, "CREATEDDATETIME" DATE NOT NULL
, "MODIFIEDUSERID" VARCHAR2(64)
, "MODIFIEDDATETIME" DATE
, "ITEMTYPE" VARCHAR2(40) NOT NULL
, "CARDID" NUMBER(38)
, "CARTID" NUMBER(38)
, "WEBACCOUNTID" NUMBER(38)
, "CUSTOMERID" NUMBER(38)
, "CUSTOMERORDERID" NUMBER(38)
, "SHIPPINGMETHODID" NUMBER(38)
, "PRODUCTID" NUMBER(38)
, "PAYASYOUGOID" NUMBER(38)
, "GOODWILLPAYMENTID" NUMBER(38)
, "ADMINISTRATIONFEEID" NUMBER(38)
, "AUTOTOPUPID" NUMBER(38)
, "CARDREFUNDABLEDEPOSITID" NUMBER(38)
, "AUTOTOPUPAMOUNT" NUMBER(9)
, "STARTDATE" DATE
, "ENDDATE" DATE
, "STARTZONE" NUMBER(3)
, "ENDZONE" NUMBER(3)
, "REMINDERDATE" VARCHAR2(40)
, "PRICE" NUMBER(9) NOT NULL
, "REFUNDCALCULATIONBASIS" VARCHAR2(40)
, "MAGNETICTICKETNUMBER" VARCHAR2(10)
, "TICKETUNUSED" VARCHAR2(10)
, "TICKETBACKDATED" VARCHAR2(10)
, "BACKDATEDREFUNDREASONID" NUMBER(38)
, "DECEASEDCUSTOMER" VARCHAR2(10)
, "TRADEDTICKETID" NUMBER(38)
, "TRADEDDATE" DATE
, "GOODWILLOTHERTEXT" VARCHAR2(100)
, "PROCESSINGDATE" DATE
, "JOURNEYDATE" DATE
, "STARTEXITSTATION" NUMBER(9)
, "PICKUPSTATION" NUMBER(9)
, "PROVIDEDSTATION" NUMBER(9)
, "REFUNDREASON" VARCHAR2(40)
, "ERRORDESCRIPTION" VARCHAR2(160)
, "JOURNEYID" NUMBER(38)
, "REFUNDTYPE" VARCHAR2(40)
, "DATEOFREFUND" DATE
, CONSTRAINT "ITEM_FK1" FOREIGN KEY ("CARDID") REFERENCES ${schemaName}."CARD"("ID")
, CONSTRAINT "ITEM_FK3" FOREIGN KEY ("CUSTOMERORDERID") REFERENCES ${schemaName}."CUSTOMERORDER"("ID")
, CONSTRAINT "ITEM_FK4" FOREIGN KEY ("SHIPPINGMETHODID") REFERENCES ${schemaName}."SHIPPINGMETHOD"("ID")
, CONSTRAINT "ITEM_FK5" FOREIGN KEY ("PRODUCTID") REFERENCES ${schemaName}."PRODUCT"("ID")
, CONSTRAINT "ITEM_FK10" FOREIGN KEY ("WEBACCOUNTID") REFERENCES ${schemaName}."WEBACCOUNT"("ID")
, CONSTRAINT "ITEM_FK10_B" FOREIGN KEY ("CUSTOMERID") REFERENCES ${schemaName}."CUSTOMER"("ID")
, CONSTRAINT "ITEM_FK12" FOREIGN KEY ("TRADEDTICKETID") REFERENCES ${schemaName}."ITEM"("ID")
, CONSTRAINT "ITEM_FK13" FOREIGN KEY ("CARTID") REFERENCES ${schemaName}."CART"("ID")
)
TABLESPACE ${tableTablespace}
;

CREATE SEQUENCE ${schemaName}.ITEM_SEQ START WITH 1 INCREMENT BY 1 NOMAXVALUE;

COMMENT ON TABLE ${schemaName}."ITEM" IS 'Shopping basket item';
COMMENT ON COLUMN ${schemaName}."ITEM"."ID" IS 'Surrogate primary key - generated from ITEM_SEQ sequence';
COMMENT ON COLUMN ${schemaName}."ITEM"."CREATEDUSERID" IS 'Who created the record';
COMMENT ON COLUMN ${schemaName}."ITEM"."CREATEDDATETIME" IS 'When (date and time) the record was created';
COMMENT ON COLUMN ${schemaName}."ITEM"."MODIFIEDUSERID" IS 'Who last modified the record';
COMMENT ON COLUMN ${schemaName}."ITEM"."MODIFIEDDATETIME" IS 'When (date and time) the record was last modified';
COMMENT ON COLUMN ${schemaName}."ITEM"."ITEMTYPE" IS 'Type of item (Product or Shipping or Card)';
COMMENT ON COLUMN ${schemaName}."ITEM"."CARDID" IS 'Reference to card';
COMMENT ON COLUMN ${schemaName}."ITEM"."CARTID" IS 'Reference to cart';
COMMENT ON COLUMN ${schemaName}."ITEM"."CUSTOMERORDERID" IS 'Reference to order';
COMMENT ON COLUMN ${schemaName}."ITEM"."SHIPPINGMETHODID" IS 'Reference to shipping method';
COMMENT ON COLUMN ${schemaName}."ITEM"."PRODUCTID" IS 'Reference to product';
COMMENT ON COLUMN ${schemaName}."ITEM"."PAYASYOUGOID" IS 'Reference to pay as you go';
COMMENT ON COLUMN ${schemaName}."ITEM"."GOODWILLPAYMENTID" IS 'Reference to goodwill payment reason';
COMMENT ON COLUMN ${schemaName}."ITEM"."ADMINISTRATIONFEEID" IS 'Reference to administration fee';
COMMENT ON COLUMN ${schemaName}."ITEM"."AUTOTOPUPID" IS 'Reference to auto top-up';
COMMENT ON COLUMN ${schemaName}."ITEM"."CARDREFUNDABLEDEPOSITID" IS 'Reference to card refundable deposit';
COMMENT ON COLUMN ${schemaName}."ITEM"."AUTOTOPUPAMOUNT" IS 'pay as you go auto top-up price';
COMMENT ON COLUMN ${schemaName}."ITEM"."STARTDATE" IS 'product start date';
COMMENT ON COLUMN ${schemaName}."ITEM"."ENDDATE" IS 'product end date';
COMMENT ON COLUMN ${schemaName}."ITEM"."STARTZONE" IS 'product start zone';
COMMENT ON COLUMN ${schemaName}."ITEM"."ENDZONE" IS 'product end zone';
COMMENT ON COLUMN ${schemaName}."ITEM"."REMINDERDATE" IS 'send an email or message to customer based on reminder date before product expired';
COMMENT ON COLUMN ${schemaName}."ITEM"."PRICE" IS 'price of the product';
COMMENT ON COLUMN ${schemaName}."ITEM"."REFUNDCALCULATIONBASIS" IS 'calculation basis of Refund Case (Ordinary or Pro Rata or Special)';
COMMENT ON COLUMN ${schemaName}."ITEM"."WEBACCOUNTID" IS 'Reference to web account';
COMMENT ON COLUMN ${schemaName}."ITEM"."CUSTOMERID" IS 'Reference to customer';
COMMENT ON COLUMN ${schemaName}."ITEM"."MAGNETICTICKETNUMBER" IS 'Paper ticket number associated with a refund';
COMMENT ON COLUMN ${schemaName}."ITEM"."TICKETUNUSED" IS 'ticket associated with a refund was unused flag';
COMMENT ON COLUMN ${schemaName}."ITEM"."TICKETBACKDATED" IS 'ticket refund to be backdated for medical reasons etc flag';
COMMENT ON COLUMN ${schemaName}."ITEM"."BACKDATEDREFUNDREASONID" IS 'foreign key linking the reason for the backdated refund';
COMMENT ON COLUMN ${schemaName}."ITEM"."DECEASEDCUSTOMER" IS 'flag to indicate that a refund should be calcuated on the basis that the customer passed away';
COMMENT ON COLUMN ${schemaName}."ITEM"."TRADEDTICKETID" IS 'links this ticket to another from which it was traded';
COMMENT ON COLUMN ${schemaName}."ITEM"."TRADEDDATE" IS 'the date a ticket was traded for another';
COMMENT ON COLUMN ${schemaName}."ITEM"."GOODWILLOTHERTEXT" IS 'text when other is selected as goodwill reason when adding goodwill item';
COMMENT ON COLUMN ${schemaName}."ITEM"."PROCESSINGDATE" IS 'Date of completion of journey';
COMMENT ON COLUMN ${schemaName}."ITEM"."JOURNEYDATE" IS 'Journey Date';
COMMENT ON COLUMN ${schemaName}."ITEM"."STARTEXITSTATION" IS 'Start/Exit station already recorded';
COMMENT ON COLUMN ${schemaName}."ITEM"."PICKUPSTATION" IS 'Station for refund pick up';
COMMENT ON COLUMN ${schemaName}."ITEM"."PROVIDEDSTATION" IS 'Station provided while completing journey';
COMMENT ON COLUMN ${schemaName}."ITEM"."REFUNDREASON" IS 'readon for refund';
COMMENT ON COLUMN ${schemaName}."ITEM"."ERRORDESCRIPTION" IS 'Error while processing refund';
COMMENT ON COLUMN ${schemaName}."ITEM"."JOURNEYID" IS 'id of the journey in TFL system';
COMMENT ON COLUMN ${schemaName}."ITEM"."REFUNDTYPE" IS 'Type of refund';
COMMENT ON COLUMN ${schemaName}."ITEM"."DATEOFREFUND" IS 'Date of Refund';


CREATE TABLE ${schemaName}."ITEM_AUD"
("REV" NUMBER NOT NULL
, "REVTYPE" NUMBER NOT NULL
,"ID" NUMBER(38) NOT NULL
, "CREATEDUSERID" VARCHAR2(64)
, "CREATEDDATETIME" DATE
, "MODIFIEDUSERID" VARCHAR2(64)
, "MODIFIEDDATETIME" DATE
, "ITEMTYPE" VARCHAR2(40)
, "CARDID" NUMBER(38)
, "CARTID" NUMBER(38)
, "WEBACCOUNTID" NUMBER(38)
, "CUSTOMERID" NUMBER(38)
, "CUSTOMERORDERID" NUMBER(38)
, "SHIPPINGMETHODID" NUMBER(38)
, "PRODUCTID" NUMBER(38)
, "PAYASYOUGOID" NUMBER(38)
, "GOODWILLPAYMENTID" NUMBER(38)
, "ADMINISTRATIONFEEID" NUMBER(38)
, "AUTOTOPUPID" NUMBER(38)
, "CARDREFUNDABLEDEPOSITID" NUMBER(38)
, "AUTOTOPUPAMOUNT" NUMBER(9)
, "STARTDATE" DATE
, "ENDDATE" DATE
, "STARTZONE" NUMBER(3)
, "ENDZONE" NUMBER(3)
, "REMINDERDATE" VARCHAR2(40)
, "PRICE" NUMBER(9, 2)
, "REFUNDCALCULATIONBASIS" VARCHAR2(40)
, "MAGNETICTICKETNUMBER" VARCHAR2(10)
, "TICKETUNUSED" VARCHAR2(10)
, "TICKETBACKDATED" VARCHAR2(10)
, "BACKDATEDREFUNDREASONID" NUMBER(38)
, "DECEASEDCUSTOMER" VARCHAR2(10)
, "TRADEDTICKETID" NUMBER(38)
, "GOODWILLOTHERTEXT" VARCHAR2(100)
, "PROCESSINGDATE" DATE
, "JOURNEYDATE" DATE
, "STARTEXITSTATION" NUMBER(9)
, "PICKUPSTATION" NUMBER(9)
, "PROVIDEDSTATION" NUMBER(9)
, "REFUNDREASON" VARCHAR2(40)
, "ERRORDESCRIPTION" VARCHAR2(160)
, "JOURNEYID" NUMBER(38)
, "REFUNDTYPE" VARCHAR2(40)
, "DATEOFREFUND" DATE
)
TABLESPACE ${tableTablespace}
;

COMMENT ON TABLE ${schemaName}."ITEM_AUD" IS 'Audit records for ITEM table';

CREATE TABLE ${schemaName}."CART_ITEM_AUD"
("REV" NUMBER NOT NULL
, "REVTYPE" NUMBER NOT NULL
,"ID" NUMBER(38) NOT NULL
, "CARTID" NUMBER(38)
)
TABLESPACE ${tableTablespace}
;

COMMENT ON TABLE ${schemaName}."CART_ITEM_AUD" IS 'Audit records for ORDER and ITEM table';

CREATE TABLE ${schemaName}."ORDER_ITEM_AUD"
("REV" NUMBER NOT NULL
, "REVTYPE" NUMBER NOT NULL
,"ID" NUMBER(38) NOT NULL
, "CUSTOMERORDERID" NUMBER(38)
)
TABLESPACE ${tableTablespace}
;

COMMENT ON TABLE ${schemaName}."ORDER_ITEM_AUD" IS 'Audit records for ORDER and ITEM table';