--liquibase formatted sql

--changeset Novacroft:11.0.86
CREATE TABLE ${schemaName}."PTTIDLOOKUP"
("ID" NUMBER(38) NOT NULL CONSTRAINT "PTTIDLOOKUP_PK" PRIMARY KEY
, "CREATEDUSERID" VARCHAR2(64) NOT NULL
, "CREATEDDATETIME" DATE NOT NULL
, "MODIFIEDUSERID" VARCHAR2(64)
, "MODIFIEDDATETIME" DATE
, "DESCRIPTION" VARCHAR2(100) NOT NULL
, "CREDIT" CHAR(1) NULL
, "DISPLAYDESCRIPTION" VARCHAR2(200) NOT NULL
)
TABLESPACE ${tableTablespace}
;

COMMENT ON TABLE ${schemaName}.PTTIDLOOKUP IS 'PTTID lookup';
COMMENT ON COLUMN ${schemaName}.PTTIDLOOKUP."ID" IS 'primary key';
COMMENT ON COLUMN ${schemaName}.PTTIDLOOKUP."DESCRIPTION" IS 'PTTID description';
COMMENT ON COLUMN ${schemaName}.PTTIDLOOKUP."CREATEDUSERID" IS 'Who created the record';
COMMENT ON COLUMN ${schemaName}.PTTIDLOOKUP."CREATEDDATETIME" IS 'When (date and time) the record was created';
COMMENT ON COLUMN ${schemaName}.PTTIDLOOKUP."MODIFIEDUSERID" IS 'Who last modified the record';
COMMENT ON COLUMN ${schemaName}.PTTIDLOOKUP."MODIFIEDDATETIME" IS 'When (date and time) the record was last modified';
COMMENT ON COLUMN ${schemaName}.PTTIDLOOKUP."CREDIT" IS 'type of Tap data';
COMMENT ON COLUMN ${schemaName}.PTTIDLOOKUP."DISPLAYDESCRIPTION" IS 'PTTID description displayed to user';