--liquibase formatted sql

--changeset Novacroft:11.0.70
CREATE TABLE ${schemaName}."CUSTOMERORDER"
("ID" NUMBER(38) NOT NULL CONSTRAINT "CUSTOMERORDER_PK" PRIMARY KEY
, "CREATEDUSERID" VARCHAR2(64) NOT NULL
, "CREATEDDATETIME" DATE NOT NULL
, "MODIFIEDUSERID" VARCHAR2(64)
, "MODIFIEDDATETIME" DATE
, "WEBACCOUNTID" NUMBER(38)
, "CUSTOMERID" NUMBER(38)
, "CARDID" NUMBER(38)
, "ORDERNUMBER" NUMBER(38) NOT NULL
, "ORDERDATE" DATE NOT NULL
, "TOTALAMOUNT" NUMBER(38) NOT NULL
, "STATUS" VARCHAR2(32) NOT NULL
, "STATIONID" NUMBER(38)
, "APPROVALID" NUMBER(38)
, "REFUNDDATE" DATE
, CONSTRAINT "CUSTOMERORDER_UK1" UNIQUE ("ORDERNUMBER")
, CONSTRAINT "CUSTOMERORDER_UK2" UNIQUE ("APPROVALID")
, CONSTRAINT "CUSTOMERORDER_FK1" FOREIGN KEY ("WEBACCOUNTID") REFERENCES ${schemaName}."WEBACCOUNT"("ID")
, CONSTRAINT "CUSTOMERORDER_FK2" FOREIGN KEY ("CUSTOMERID") REFERENCES ${schemaName}."CUSTOMER"("ID")
, CONSTRAINT "CUSTOMERORDER_FK3" FOREIGN KEY ("CARDID") REFERENCES ${schemaName}."CARD"("ID")
)
TABLESPACE ${tableTablespace}
;

CREATE INDEX ${schemaName}."CUSTOMERORDER_IDX1"
ON ${schemaName}."CUSTOMERORDER"
("CUSTOMERID")
TABLESPACE ${indexTablespace}
;

CREATE SEQUENCE ${schemaName}."CUSTOMERORDER_SEQ";
CREATE SEQUENCE ${schemaName}."ORDER_NUMBER_SEQ" START WITH 100000 NOCACHE ORDER;

COMMENT ON TABLE ${schemaName}."CUSTOMERORDER" IS 'Order';
COMMENT ON COLUMN ${schemaName}."CUSTOMERORDER"."ID" IS 'Surrogate primary key - generated from CUSTOMERORDER_SEQ sequence';
COMMENT ON COLUMN ${schemaName}."CUSTOMERORDER"."CREATEDUSERID" IS 'Who created the record';
COMMENT ON COLUMN ${schemaName}."CUSTOMERORDER"."CREATEDDATETIME" IS 'When (date and time) the record was created';
COMMENT ON COLUMN ${schemaName}."CUSTOMERORDER"."MODIFIEDUSERID" IS 'Who last modified the record';
COMMENT ON COLUMN ${schemaName}."CUSTOMERORDER"."MODIFIEDDATETIME" IS 'When (date and time) the record was last modified';
COMMENT ON COLUMN ${schemaName}."CUSTOMERORDER"."WEBACCOUNTID" IS 'Reference to web account';
COMMENT ON COLUMN ${schemaName}."CUSTOMERORDER"."CUSTOMERID" IS 'Reference to customer';
COMMENT ON COLUMN ${schemaName}."CUSTOMERORDER"."CARDID" IS 'Reference to card';
COMMENT ON COLUMN ${schemaName}."CUSTOMERORDER"."ORDERNUMBER" IS 'Reference number for order - generated from ORDER_NUMBER_SEQ sequence';
COMMENT ON COLUMN ${schemaName}."CUSTOMERORDER"."ORDERDATE" IS 'Date order was made';
COMMENT ON COLUMN ${schemaName}."CUSTOMERORDER"."TOTALAMOUNT" IS 'Total value of order (in pence): positive for payment; and negative for refund';
COMMENT ON COLUMN ${schemaName}."CUSTOMERORDER"."STATUS" IS 'Current status of order';
COMMENT ON COLUMN ${schemaName}."CUSTOMERORDER"."APPROVALID" IS 'Reference number for workflow';
COMMENT ON COLUMN ${schemaName}."CUSTOMERORDER"."REFUNDDATE" IS 'Date the refund was created';

CREATE TABLE ${schemaName}."CUSTOMERORDER_AUD"
("REV" NUMBER NOT NULL
, "REVTYPE" NUMBER NOT NULL
,"ID" NUMBER(38) NOT NULL
, "CREATEDUSERID" VARCHAR2(64)
, "CREATEDDATETIME" DATE
, "MODIFIEDUSERID" VARCHAR2(64)
, "MODIFIEDDATETIME" DATE
, "WEBACCOUNTID" NUMBER(38)
, "CUSTOMERID" NUMBER(38)
, "CARDID" NUMBER(38)
, "ORDERNUMBER" NUMBER(38)
, "ORDERDATE" DATE
, "TOTALAMOUNT" NUMBER(38)
, "STATUS" VARCHAR2(32)
, "STATIONID" NUMBER(38)
, "APPROVALID" NUMBER(38)
, "REFUNDDATE" DATE
)
TABLESPACE ${tableTablespace}
;

COMMENT ON TABLE ${schemaName}."CUSTOMERORDER_AUD" IS 'Audit records for CUSTOMERORDER table';
